using System.Data;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace AyGest.Wpf;

public partial class MainWindow
{
    static readonly bool ConfigurationNavigationHook = RegisterConfigurationNavigation();
    static bool RegisterConfigurationNavigation(){EventManager.RegisterClassHandler(typeof(MainWindow),Window.LoadedEvent,new RoutedEventHandler(AddConfigurationNavigation));return true;}
    static void AddConfigurationNavigation(object sender,RoutedEventArgs e){if(sender is not MainWindow w)return;var root=FindConfigurationPanels(w.Content as DependencyObject).FirstOrDefault(p=>p.Children.OfType<Button>().Any(b=>ConfigButtonText(b)=="Configurações"));if(root is null||root.Children.OfType<Button>().Any(b=>ConfigButtonText(b)=="Cadastros"))return;var settings=root.Children.OfType<Button>().FirstOrDefault(b=>ConfigButtonText(b)=="Configurações");var index=settings is null?root.Children.Count:root.Children.IndexOf(settings);root.Children.Insert(index,w.ConfigurationNav("Cadastros","\uE71D",(_,__)=>w.ConfigurationHub_Click()));}
    static IEnumerable<StackPanel> FindConfigurationPanels(DependencyObject? root){if(root is StackPanel p)yield return p;if(root is null)yield break;for(var i=0;i<VisualTreeHelper.GetChildrenCount(root);i++)foreach(var x in FindConfigurationPanels(VisualTreeHelper.GetChild(root,i)))yield return x;}
    static string ConfigButtonText(Button b)=>b.Content is StackPanel p?p.Children.OfType<TextBlock>().LastOrDefault()?.Text??"":b.Content?.ToString()??"";
    Button ConfigurationNav(string text,string icon,RoutedEventHandler click){var b=new Button{Style=(Style)FindResource("SidebarButton"),Content=new StackPanel{Orientation=Orientation.Horizontal}};var p=(StackPanel)b.Content;p.Children.Add(new TextBlock{Text=icon,FontFamily=new FontFamily("Segoe MDL2 Assets"),FontSize=15,Width=28});p.Children.Add(new TextBlock{Text=text,VerticalAlignment=VerticalAlignment.Center});b.Click+=click;return b;}
    void ConfigurationHub_Click(){try{extended.EnsureSchema();}catch(Exception ex){Error(ex);return;}var p=new StackPanel();p.Children.Add(Header("Cadastros e configurações","Tudo o que controla o comportamento do AyGest fica configurável",B("Métodos de pagamento",(_,__)=>PaymentMethods_Click()),B("Categorias",(_,__)=>Categories_Click()),B("Unidades",(_,__)=>Units_Click()),B("Taxas de IVA",(_,__)=>TaxRates_Click()),B("Séries",(_,__)=>Series_Click()),Secondary("Permissões",(_,__)=>Permissions_Click())));var cards=new UniformGrid{Columns=3,Margin=new Thickness(0,14,0,10)};AddCountCard(cards,"Métodos de pagamento","SELECT COUNT(*) FROM payment_methods WHERE company_id=@c","Método");AddCountCard(cards,"Categorias","SELECT COUNT(*) FROM categories WHERE company_id=@c","Categoria");AddCountCard(cards,"Unidades","SELECT COUNT(*) FROM units WHERE company_id=@c","Unidade");AddCountCard(cards,"Taxas de IVA","SELECT COUNT(*) FROM tax_rates WHERE company_id=@c","Taxa");AddCountCard(cards,"Séries","SELECT COUNT(*) FROM document_series WHERE company_id=@c","Série");AddCountCard(cards,"Armazéns","SELECT COUNT(*) FROM warehouses WHERE company_id=@c","Armazém");p.Children.Add(cards);Show("Cadastros e configurações",p);}
    void AddCountCard(Panel parent,string title,string sql,string unit){var r=svc.Query(sql,("@c",companyId)).Rows.FirstOrDefault();var count=Convert.ToInt32(r?[0]??0);var label=count==1?unit:$"{unit}s";parent.Children.Add(Card(title,$"{count} {label}"));}
    void PaymentMethods_Click(){var p=Header("Métodos de pagamento","Crie, edite e desactive os meios aceites no POS",B("+ Novo método",(_,__)=>EditPaymentMethod(null)),Secondary("Activar/desactivar",(_,__)=>ToggleSelected("payment_methods",PaymentMethods_Click)));grid=Table("SELECT id,name,code,active,requires_reference,sort_order FROM payment_methods WHERE company_id=@c ORDER BY sort_order,name",("@c",companyId));grid.MouseDoubleClick+=(s,e)=>EditPaymentMethod(grid.SelectedItem as DataRowView);p.Children.Add(grid);Show("Métodos de pagamento",p);}
    void EditPaymentMethod(DataRowView? row){var f=Form(row==null?"Novo método":"Editar método",("Nome",row?["name"]?.ToString()??""),("Código",row?["code"]?.ToString()??""),("Ordem",row?["sort_order"]?.ToString()??"0"),("Exige referência (1/0)",row?["requires_reference"]?.ToString()??"0"));if(f==null)return;try{if(string.IsNullOrWhiteSpace(f[0])||string.IsNullOrWhiteSpace(f[1]))throw new InvalidOperationException("Nome e código são obrigatórios.");var order=int.Parse(f[2]);var reference=f[3]=="1"?1:0;if(row==null)svc.Execute("INSERT INTO payment_methods(company_id,name,code,sort_order,requires_reference) VALUES(@c,@n,@co,@o,@r)",("@c",companyId),("@n",f[0]),("@co",f[1].ToUpperInvariant()),("@o",order),("@r",reference));else svc.Execute("UPDATE payment_methods SET name=@n,code=@co,sort_order=@o,requires_reference=@r WHERE id=@i AND company_id=@c",("@n",f[0]),("@co",f[1].ToUpperInvariant()),("@o",order),("@r",reference),("@i",Convert.ToInt64(row["id"])),("@c",companyId));PaymentMethods_Click();}catch(Exception ex){Error(ex);}}
    void Categories_Click(){var p=Header("Categorias","Organize o catálogo sem alterar código",B("+ Nova categoria",(_,__)=>EditCategory(null)),Secondary("Activar/desactivar",(_,__)=>ToggleSelected("categories",Categories_Click)));grid=Table("SELECT id,name,active FROM categories WHERE company_id=@c ORDER BY name",("@c",companyId));grid.MouseDoubleClick+=(s,e)=>EditCategory(grid.SelectedItem as DataRowView);p.Children.Add(grid);Show("Categorias",p);}
    void EditCategory(DataRowView? row){var f=Form(row==null?"Nova categoria":"Editar categoria",("Nome",row?["name"]?.ToString()??""));if(f==null)return;try{if(string.IsNullOrWhiteSpace(f[0]))throw new InvalidOperationException("O nome é obrigatório.");if(row==null)svc.Execute("INSERT INTO categories(company_id,name) VALUES(@c,@n)",("@c",companyId),("@n",f[0]));else svc.Execute("UPDATE categories SET name=@n WHERE id=@i AND company_id=@c",("@n",f[0]),("@i",Convert.ToInt64(row["id"])),("@c",companyId));Categories_Click();}catch(Exception ex){Error(ex);}}
    void Units_Click(){var p=Header("Unidades","Unidades de medida usadas nos produtos",B("+ Nova unidade",(_,__)=>EditUnit(null)),Secondary("Activar/desactivar",(_,__)=>ToggleSelected("units",Units_Click)));grid=Table("SELECT id,name,abbreviation,active FROM units WHERE company_id=@c ORDER BY name",("@c",companyId));grid.MouseDoubleClick+=(s,e)=>EditUnit(grid.SelectedItem as DataRowView);p.Children.Add(grid);Show("Unidades",p);}
    void EditUnit(DataRowView? row){var f=Form(row==null?"Nova unidade":"Editar unidade",("Nome",row?["name"]?.ToString()??""),("Abreviatura",row?["abbreviation"]?.ToString()??""));if(f==null)return;try{if(string.IsNullOrWhiteSpace(f[0])||string.IsNullOrWhiteSpace(f[1]))throw new InvalidOperationException("Nome e abreviatura são obrigatórios.");if(row==null)svc.Execute("INSERT INTO units(company_id,name,abbreviation) VALUES(@c,@n,@a)",("@c",companyId),("@n",f[0]),("@a",f[1]));else svc.Execute("UPDATE units SET name=@n,abbreviation=@a WHERE id=@i AND company_id=@c",("@n",f[0]),("@a",f[1]),("@i",Convert.ToInt64(row["id"])),("@c",companyId));Units_Click();}catch(Exception ex){Error(ex);}}
    void TaxRates_Click(){var p=Header("Taxas de IVA","Defina as taxas utilizadas pela empresa",B("+ Nova taxa",(_,__)=>EditTax(null)),Secondary("Activar/desactivar",(_,__)=>ToggleSelected("tax_rates",TaxRates_Click)));grid=Table("SELECT id,name,rate,active FROM tax_rates WHERE company_id=@c ORDER BY rate,name",("@c",companyId));grid.MouseDoubleClick+=(s,e)=>EditTax(grid.SelectedItem as DataRowView);p.Children.Add(grid);Show("Taxas de IVA",p);}
    void EditTax(DataRowView? row){var f=Form(row==null?"Nova taxa":"Editar taxa",("Nome",row?["name"]?.ToString()??""),("Taxa %",row?["rate"]?.ToString()??"0"));if(f==null)return;try{var rate=D(f[1]);if(rate<0||rate>100)throw new InvalidOperationException("A taxa deve estar entre 0 e 100%.");if(row==null)svc.Execute("INSERT INTO tax_rates(company_id,name,rate) VALUES(@c,@n,@r)",("@c",companyId),("@n",f[0]),("@r",rate));else svc.Execute("UPDATE tax_rates SET name=@n,rate=@r WHERE id=@i AND company_id=@c",("@n",f[0]),("@r",rate),("@i",Convert.ToInt64(row["id"])),("@c",companyId));TaxRates_Click();}catch(Exception ex){Error(ex);}}
    void Series_Click(){var p=Header("Séries de documentos","Numeração configurável para documentos",B("+ Nova série",(_,__)=>EditSeries(null)),Secondary("Activar/desactivar",(_,__)=>ToggleSelected("document_series",Series_Click)));grid=Table("SELECT id,name,prefix,next_number,active FROM document_series WHERE company_id=@c ORDER BY name",("@c",companyId));grid.MouseDoubleClick+=(s,e)=>EditSeries(grid.SelectedItem as DataRowView);p.Children.Add(grid);Show("Séries",p);}
    void EditSeries(DataRowView? row){var f=Form(row==null?"Nova série":"Editar série",("Nome",row?["name"]?.ToString()??""),("Prefixo",row?["prefix"]?.ToString()??""),("Próximo número",row?["next_number"]?.ToString()??"1"));if(f==null)return;try{var n=long.Parse(f[2]);if(n<1)throw new InvalidOperationException("O próximo número deve ser maior que zero.");if(row==null)svc.Execute("INSERT INTO document_series(company_id,name,prefix,next_number) VALUES(@c,@n,@p,@x)",("@c",companyId),("@n",f[0]),("@p",f[1].ToUpperInvariant()),("@x",n));else svc.Execute("UPDATE document_series SET name=@n,prefix=@p,next_number=@x WHERE id=@i AND company_id=@c",("@n",f[0]),("@p",f[1].ToUpperInvariant()),("@x",n),("@i",Convert.ToInt64(row["id"])),("@c",companyId));Series_Click();}catch(Exception ex){Error(ex);}}
    void Permissions_Click(){var permissions=new[]{"CREATE_INVOICE","CANCEL_INVOICE","CHANGE_PRICE","DISCOUNT","STOCK_ADJUST","CASH_OPEN","CASH_CLOSE","VIEW_PROFIT","MANAGE_USERS","MANAGE_SETTINGS","EXPORT_DATA"};var p=Header("Permissões","Controle operacional por função");foreach(var role in new[]{"Administrator","Manager","Cashier","Stock"}){var g=new GroupBox{Header=role};var list=new StackPanel();foreach(var permission in permissions){var cb=new CheckBox{Content=permission,IsChecked=PermissionValue(role,permission)};var captured=permission;cb.Checked+=(s,e)=>SetPermission(role,captured,true);cb.Unchecked+=(s,e)=>SetPermission(role,captured,false);list.Children.Add(cb);}g.Content=list;p.Children.Add(g);}Show("Permissões",p);}
    bool PermissionValue(string role,string permission){var r=svc.Query("SELECT allowed FROM app_permissions WHERE company_id=@c AND role=@r AND permission=@p",("@c",companyId),("@r",role),("@p",permission)).Rows.FirstOrDefault();if(r is null)return role=="Administrator";return Convert.ToInt32(r[0])==1;}
    void SetPermission(string role,string permission,bool allowed)=>svc.Execute("INSERT INTO app_permissions(company_id,role,permission,allowed) VALUES(@c,@r,@p,@a) ON CONFLICT(company_id,role,permission) DO UPDATE SET allowed=excluded.allowed",("@c",companyId),("@r",role),("@p",permission),("@a",allowed?1:0));
    void ToggleSelected(string table,Action refresh){if(grid.SelectedItem is not DataRowView r)return;try{svc.Execute($"UPDATE {table} SET active=CASE WHEN active=1 THEN 0 ELSE 1 END WHERE id=@i AND company_id=@c",("@i",Convert.ToInt64(r["id"])),("@c",companyId));refresh();}catch(Exception ex){Error(ex);}}
}
