using Microsoft.Data.Sqlite;using System.Collections.ObjectModel;using System.Text;using System.Windows;using System.Windows.Controls;using System.IO;
namespace AyGest.Wpf;
public partial class CustomersWindow:Window{
 readonly string _db=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AyGest","aygest.db");readonly ObservableCollection<CustomerEditorWindow.CustomerRow> _all=new();
 public CustomersWindow(){InitializeComponent();Directory.CreateDirectory(Path.GetDirectoryName(_db)!);EnsureSchema();CustomersGrid.ItemsSource=_all;Load();}
 SqliteConnection C()=>new($"Data Source={_db}");
 void EnsureSchema(){using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,type TEXT NOT NULL DEFAULT 'Particular',name TEXT NOT NULL,tax_id TEXT,phone TEXT,email TEXT,website TEXT,address TEXT,city TEXT,contact_person TEXT,credit_limit REAL NOT NULL DEFAULT 0,payment_terms TEXT,notes TEXT,status TEXT NOT NULL DEFAULT 'Activo',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);";q.ExecuteNonQuery();}
 void Load(){_all.Clear();using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="SELECT c.id,c.code,c.type,c.name,COALESCE(c.tax_id,''),COALESCE(c.phone,''),COALESCE(c.email,''),COALESCE(c.website,''),COALESCE(c.address,''),COALESCE(c.city,''),COALESCE(c.contact_person,''),c.credit_limit,COALESCE(c.payment_terms,''),c.status,COALESCE(c.notes,''),(SELECT COUNT(*) FROM invoices i WHERE i.customer_id=c.id),(SELECT COALESCE(SUM(i.total),0) FROM invoices i WHERE i.customer_id=c.id AND i.status<>'cancelled'),(SELECT COALESCE(SUM(i.total),0) FROM invoices i WHERE i.customer_id=c.id AND i.status='pending') FROM customers c ORDER BY c.name";try{using var r=q.ExecuteReader();while(r.Read())_all.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),r.GetString(8),r.GetString(9),r.GetString(10),r.GetDecimal(11),r.GetString(12),r.GetString(13),r.GetString(14),r.GetInt32(15),r.GetDecimal(16),r.GetDecimal(17)));}catch(SqliteException){using var r2=c.CreateCommand();r2.CommandText="SELECT id,code,type,name,COALESCE(tax_id,''),COALESCE(phone,''),COALESCE(email,''),COALESCE(website,''),COALESCE(address,''),COALESCE(city,''),COALESCE(contact_person,''),credit_limit,COALESCE(payment_terms,''),status,COALESCE(notes,'') FROM customers ORDER BY name";using var r=r2.ExecuteReader();while(r.Read())_all.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),r.GetString(8),r.GetString(9),r.GetString(10),r.GetDecimal(11),r.GetString(12),r.GetString(13),r.GetString(14),0,0,0));}Apply();}
 void Apply(){var t=(SearchBox.Text??"").Trim().ToLowerInvariant();var type=(TypeBox.SelectedItem as ComboBoxItem)?.Content?.ToString();var st=(StatusBox.SelectedItem as ComboBoxItem)?.Content?.ToString();var list=_all.Where(x=>(t==""||$"{x.Code} {x.Name} {x.TaxId} {x.Phone} {x.Email}".ToLowerInvariant().Contains(t))&&(type=="Todos os tipos"||type==null||x.Type==type)&&(st=="Todos os estados"||st==null||x.Status==st.Replace("Activos","Activo").Replace("Inactivos","Inactivo"))).ToList();CustomersGrid.ItemsSource=list;CountText.Content=list.Count.ToString();SalesText.Content=list.Sum(x=>x.TotalSpent).ToString("N2")+" MT";BalanceText.Content=list.Sum(x=>x.Balance).ToString("N2")+" MT";}
 void FilterChanged(object s,EventArgs e)=>Apply();void Refresh_Click(object s,RoutedEventArgs e)=>Load();
 void New_Click(object s,RoutedEventArgs e){var d=new CustomerEditorWindow{Owner=this};if(d.ShowDialog()==true){Save(d,null);Load();}}
 void Edit_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is not CustomerEditorWindow.CustomerRow x)return;var d=new CustomerEditorWindow(x){Owner=this};if(d.ShowDialog()==true){Save(d,x.Id);Load();}}
 void Save(CustomerEditorWindow d,long? id){using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText=id==null?"INSERT INTO customers(code,type,name,tax_id,phone,email,website,address,city,contact_person,credit_limit,payment_terms,notes,status,created_at,updated_at) VALUES($c,$t,$n,$tax,$p,$e,$w,$a,$city,$cp,$cl,$pt,$no,$s,$d,$d)":"UPDATE customers SET type=$t,name=$n,tax_id=$tax,phone=$p,email=$e,website=$w,address=$a,city=$city,contact_person=$cp,credit_limit=$cl,payment_terms=$pt,notes=$no,status=$s,updated_at=$d WHERE id=$id";if(id!=null)q.Parameters.AddWithValue("$id",id);q.Parameters.AddWithValue("$c",string.IsNullOrWhiteSpace(d.Code)?"CLI"+DateTime.Now.ToString("yyyyMMddHHmmss"):d.Code);q.Parameters.AddWithValue("$t",d.Type);q.Parameters.AddWithValue("$n",d.Name);q.Parameters.AddWithValue("$tax",d.TaxId);q.Parameters.AddWithValue("$p",d.Phone);q.Parameters.AddWithValue("$e",d.Email);q.Parameters.AddWithValue("$w",d.Website);q.Parameters.AddWithValue("$a",d.Address);q.Parameters.AddWithValue("$city",d.City);q.Parameters.AddWithValue("$cp",d.Contact);q.Parameters.AddWithValue("$cl",decimal.TryParse(d.CreditLimit.Replace(".",","),out var cl)?cl:0);q.Parameters.AddWithValue("$pt",d.PaymentTerms);q.Parameters.AddWithValue("$no",d.Notes);q.Parameters.AddWithValue("$s",d.Status);q.Parameters.AddWithValue("$d",DateTime.UtcNow.ToString("O"));q.ExecuteNonQuery();}
 void History_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is CustomerEditorWindow.CustomerRow x)MessageBox.Show($"{x.Name}\n\nFacturas: {x.PurchaseCount}\nTotal comprado: {x.TotalSpent:N2} MT\nSaldo pendente: {x.Balance:N2} MT","Histórico do cliente",MessageBoxButton.OK,MessageBoxImage.Information);}
 void Account_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is CustomerEditorWindow.CustomerRow x)MessageBox.Show($"Conta corrente\n\nLimite de crédito: {x.CreditLimit:N2} MT\nSaldo: {x.Balance:N2} MT\nDisponível: {Math.Max(0,x.CreditLimit-x.Balance):N2} MT\nCondições: {x.PaymentTerms}","Conta do cliente",MessageBoxButton.OK,MessageBoxImage.Information);}
 void More_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is not CustomerEditorWindow.CustomerRow x)return;if(MessageBox.Show($"Alterar o estado de {x.Name}?","Cliente",MessageBoxButton.YesNo,MessageBoxImage.Question)!=MessageBoxResult.Yes)return;using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="UPDATE customers SET status=CASE WHEN status='Activo' THEN 'Inactivo' ELSE 'Activo' END,updated_at=$d WHERE id=$id";q.Parameters.AddWithValue("$id",x.Id);q.Parameters.AddWithValue("$d",DateTime.UtcNow.ToString("O"));q.ExecuteNonQuery();Load();}
 void Export_Click(object s,RoutedEventArgs e){var sb=new StringBuilder("Código;Tipo;Cliente;NUIT;Contacto;Email;Compras;Total;Saldo;Estado\n");foreach(var x in _all)sb.AppendLine($"{x.Code};{x.Type};{x.Name};{x.TaxId};{x.Phone};{x.Email};{x.PurchaseCount};{x.TotalSpent:N2};{x.Balance:N2};{x.Status}");var p=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"AyGest_Clientes.csv");File.WriteAllText(p,sb.ToString(),Encoding.UTF8);MessageBox.Show("Exportação concluída:\n"+p,"Clientes",MessageBoxButton.OK,MessageBoxImage.Information);}
}
