using System.Windows;using System.Windows.Controls;
namespace AyGest.Wpf;
public partial class CustomerEditorWindow:Window{
 public string Code=>CodeBox.Text.Trim();public string Type=>(TypeBox.SelectedItem as ComboBoxItem)?.Content?.ToString()??"Particular";public string Name=>NameBox.Text.Trim();public string TaxId=>TaxIdBox.Text.Trim();public string Phone=>PhoneBox.Text.Trim();public string Email=>EmailBox.Text.Trim();public string Website=>WebsiteBox.Text.Trim();public string Address=>AddressBox.Text.Trim();public string City=>CityBox.Text.Trim();public string Contact=>ContactBox.Text.Trim();public string CreditLimit=>CreditLimitBox.Text.Trim();public string PaymentTerms=>PaymentTermsBox.Text.Trim();public string Status=>(StatusBox.SelectedItem as ComboBoxItem)?.Content?.ToString()??"Activo";public string Notes=>NotesBox.Text.Trim();
 public CustomerEditorWindow(){InitializeComponent();}
 public CustomerEditorWindow(CustomerRow x):this(){CodeBox.Text=x.Code;CodeBox.IsEnabled=false;TypeBox.SelectedIndex=x.Type=="Empresa"?1:0;NameBox.Text=x.Name;TaxIdBox.Text=x.TaxId;PhoneBox.Text=x.Phone;EmailBox.Text=x.Email;WebsiteBox.Text=x.Website;AddressBox.Text=x.Address;CityBox.Text=x.City;ContactBox.Text=x.Contact;CreditLimitBox.Text=x.CreditLimit.ToString("N2");PaymentTermsBox.Text=x.PaymentTerms;StatusBox.SelectedIndex=x.Status=="Activo"?0:1;NotesBox.Text=x.Notes;}
 void Save_Click(object s,RoutedEventArgs e){if(string.IsNullOrWhiteSpace(Name)){MessageBox.Show("O nome do cliente é obrigatório.","Validação",MessageBoxButton.OK,MessageBoxImage.Warning);return;}if(!string.IsNullOrWhiteSpace(Email)&&!Email.Contains('@')){MessageBox.Show("Introduza um e-mail válido.","Validação",MessageBoxButton.OK,MessageBoxImage.Warning);return;}if(!decimal.TryParse(CreditLimitBox.Text.Replace(".",","),out _)&&!string.IsNullOrWhiteSpace(CreditLimitBox.Text)){MessageBox.Show("O limite de crédito deve ser numérico.","Validação",MessageBoxButton.OK,MessageBoxImage.Warning);return;}DialogResult=true;}
 void Cancel_Click(object s,RoutedEventArgs e)=>DialogResult=false;
 public record CustomerRow(long Id,string Code,string Type,string Name,string TaxId,string Phone,string Email,string Website,string Address,string City,string Contact,decimal CreditLimit,string PaymentTerms,string Status,string Notes,int PurchaseCount,decimal TotalSpent,decimal Balance);
}
