using Microsoft.Data.Sqlite;using System.Collections.ObjectModel;using System.Text;using System.Windows;using System.Windows.Controls;using System.IO;
namespace AyGest.Wpf;
public partial class FinanceCashWindow:Window{
 readonly string _db=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AyGest","aygest.db");readonly ObservableCollection<MoveRow> _all=new();
 public FinanceCashWindow(){InitializeComponent();Directory.CreateDirectory(Path.GetDirectoryName(_db)!);EnsureSchema();MovementsGrid.ItemsSource=_all;Load();}
 SqliteConnection C()=>new($"Data Source={_db}");
 void EnsureSchema(){using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="CREATE TABLE IF NOT EXISTS cash_sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,opened_at TEXT NOT NULL,closed_at TEXT,opening_balance REAL NOT NULL DEFAULT 0,closing_balance REAL,expected_balance REAL,status TEXT NOT NULL DEFAULT 'Aberto',notes TEXT);CREATE TABLE IF NOT EXISTS cash_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,session_id INTEGER,type TEXT NOT NULL,description TEXT,reference TEXT,method TEXT,amount REAL NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS accounts_receivable(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER,description TEXT,total REAL NOT NULL,paid REAL NOT NULL DEFAULT 0,due_date TEXT,status TEXT NOT NULL DEFAULT 'Pendente');CREATE TABLE IF NOT EXISTS accounts_payable(id INTEGER PRIMARY KEY AUTOINCREMENT,supplier_id INTEGER,description TEXT,total REAL NOT NULL,paid REAL NOT NULL DEFAULT 0,due_date TEXT,status TEXT NOT NULL DEFAULT 'Pendente');";q.ExecuteNonQuery();}
 void Load(){_all.Clear();using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="SELECT id,created_at,type,COALESCE(description,''),COALESCE(reference,''),COALESCE(method,''),CASE WHEN type IN ('Recebimento','Entrada') THEN amount ELSE 0 END,CASE WHEN type IN ('Pagamento','Saída') THEN amount ELSE 0 END FROM cash_movements ORDER BY id DESC";using var r=q.ExecuteReader();decimal bal=0;var rows=new List<MoveRow>();while(r.Read())rows.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetDecimal(6),r.GetDecimal(7),0));foreach(var x in rows.AsEnumerable().Reverse()){bal+=x.Inflow-x.Outflow;_all.Insert(0,x with{Balance=bal});}Apply();}
 void Apply(){var t=(SearchBox.Text??"").Trim().ToLowerInvariant();var type=(TypeBox.SelectedItem as ComboBoxItem)?.Content?.ToString();DateTime? from=FromDate.SelectedDate,to=ToDate.SelectedDate;var list=_all.Where(x=>(t==""||$"{x.Description} {x.Reference} {x.Method}".ToLowerInvariant().Contains(t))&&(type=="Todos os tipos"||type==null||x.Type==type)&&(!from.HasValue||DateTime.TryParse(x.Date,out var d)&&d.Date>=from.Value.Date)&&(!to.HasValue||DateTime.TryParse(x.Date,out var d2)&&d2.Date<=to.Value.Date)).ToList();MovementsGrid.ItemsSource=list;CountText.Content=list.Count;var ins=list.Sum(x=>x.Inflow);var outs=list.Sum(x=>x.Outflow);TotalInText.Content=ins.ToString("N2")+" MT";TotalOutText.Content=outs.ToString("N2")+" MT";BalanceText.Text=(ins-outs).ToString("N2")+" MT";var today=_all.Where(x=>DateTime.TryParse(x.Date,out var d)&&d.Date==DateTime.Today);InText.Text=today.Sum(x=>x.Inflow).ToString("N2")+" MT";OutText.Text=today.Sum(x=>x.Outflow).ToString("N2")+" MT";ReceivableText.Text=OpenAmount("accounts_receivable");PayableText.Text=OpenAmount("accounts_payable");}
 string OpenAmount(string table){using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText=$"SELECT COALESCE(SUM(total-paid),0) FROM {table} WHERE status<>'Pago' AND total>paid";return Convert.ToDecimal(q.ExecuteScalar()).ToString("N2")+" MT";}
 void FilterChanged(object s,EventArgs e)=>Apply();void Refresh_Click(object s,RoutedEventArgs e)=>Load();
 void OpenCash_Click(object s,RoutedEventArgs e){using var c=C();c.Open();using var check=c.CreateCommand();check.CommandText="SELECT COUNT(*) FROM cash_sessions WHERE status='Aberto'";if(Convert.ToInt32(check.ExecuteScalar())>0){MessageBox.Show("Já existe um caixa aberto.");return;}var v=Microsoft.VisualBasic.Interaction.InputBox("Saldo inicial do caixa:","Abrir caixa","0");if(!decimal.TryParse(v.Replace(".",","),out var amount)||amount<0)return;using var q=c.CreateCommand();q.CommandText="INSERT INTO cash_sessions(opened_at,opening_balance,status) VALUES($d,$v,'Aberto')";q.Parameters.AddWithValue("$d",DateTime.UtcNow.ToString("O"));q.Parameters.AddWithValue("$v",amount);q.ExecuteNonQuery();MessageBox.Show("Caixa aberto com sucesso.");}
 void CloseCash_Click(object s,RoutedEventArgs e){using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="SELECT id,opening_balance FROM cash_sessions WHERE status='Aberto' ORDER BY id DESC LIMIT 1";using var r=q.ExecuteReader();if(!r.Read()){MessageBox.Show("Não existe caixa aberto.");return;}var id=r.GetInt64(0);var opening=r.GetDecimal(1);r.Close();using var m=c.CreateCommand();m.CommandText="SELECT COALESCE(SUM(CASE WHEN type IN ('Recebimento','Entrada') THEN amount ELSE -amount END),0) FROM cash_movements WHERE session_id=$id";m.Parameters.AddWithValue("$id",id);var expected=opening+Convert.ToDecimal(m.ExecuteScalar());var actual=Microsoft.VisualBasic.Interaction.InputBox($"Saldo esperado: {expected:N2} MT\nInforme o saldo contado:","Fechar caixa",expected.ToString("N2"));if(!decimal.TryParse(actual.Replace(".",","),out var close))return;using var u=c.CreateCommand();u.CommandText="UPDATE cash_sessions SET closed_at=$d,closing_balance=$c,expected_balance=$e,status='Fechado' WHERE id=$id";u.Parameters.AddWithValue("$d",DateTime.UtcNow.ToString("O"));u.Parameters.AddWithValue("$c",close);u.Parameters.AddWithValue("$e",expected);u.Parameters.AddWithValue("$id",id);u.ExecuteNonQuery();MessageBox.Show($"Caixa fechado.\nEsperado: {expected:N2} MT\nContado: {close:N2} MT\nDiferença: {close-expected:N2} MT");}
 void Movement_Click(object s,RoutedEventArgs e){var type=Microsoft.VisualBasic.Interaction.InputBox("Tipo (Recebimento, Pagamento, Transferência ou Ajuste):","Movimento","Recebimento").Trim();if(string.IsNullOrWhiteSpace(type))return;var desc=Microsoft.VisualBasic.Interaction.InputBox("Descrição:","Movimento","");var amountText=Microsoft.VisualBasic.Interaction.InputBox("Valor:","Movimento","0");if(!decimal.TryParse(amountText.Replace(".",","),out var amount)||amount<=0)return;var method=Microsoft.VisualBasic.Interaction.InputBox("Método de pagamento:","Movimento","Dinheiro");var reference=Microsoft.VisualBasic.Interaction.InputBox("Referência/documento:","Movimento","");using var c=C();c.Open();using var session=c.CreateCommand();session.CommandText="SELECT id FROM cash_sessions WHERE status='Aberto' ORDER BY id DESC LIMIT 1";var sid=session.ExecuteScalar();if(sid==null){MessageBox.Show("Abra o caixa primeiro.");return;}using var q=c.CreateCommand();q.CommandText="INSERT INTO cash_movements(session_id,type,description,reference,method,amount,created_at) VALUES($s,$t,$d,$r,$m,$a,$date)";q.Parameters.AddWithValue("$s",sid);q.Parameters.AddWithValue("$t",type);q.Parameters.AddWithValue("$d",desc);q.Parameters.AddWithValue("$r",reference);q.Parameters.AddWithValue("$m",method);q.Parameters.AddWithValue("$a",amount);q.Parameters.AddWithValue("$date",DateTime.UtcNow.ToString("O"));q.ExecuteNonQuery();Load();}
 void Export_Click(object s,RoutedEventArgs e){var sb=new StringBuilder("Data;Tipo;Descrição;Documento;Método;Entrada;Saída;Saldo\n");foreach(var x in _all)sb.AppendLine($"{x.Date};{x.Type};{x.Description};{x.Reference};{x.Method};{x.Inflow:N2};{x.Outflow:N2};{x.Balance:N2}");var p=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"AyGest_Financeiro.csv");File.WriteAllText(p,sb.ToString(),Encoding.UTF8);MessageBox.Show("Exportação concluída:\n"+p);}
 public record MoveRow(long Id,string Date,string Type,string Description,string Reference,string Method,decimal Inflow,decimal Outflow,decimal Balance);
}
