using System.Data;
using System.Security.Cryptography;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Microsoft.Win32;
using AyGest.Wpf.Services;
namespace AyGest.Wpf;
public partial class MainWindow : Window
{
 readonly Data.AppDb db=new(); readonly BusinessService svc; readonly long companyId; DataGrid grid=new(); OnlineApiClient? online;
 public MainWindow(){InitializeComponent();svc=new BusinessService(db);companyId=svc.EnsureCompany();Dashboard_Click(this,new RoutedEventArgs());}
 Button B(string text,RoutedEventHandler click){var b=new Button{Content=text,Margin=new Thickness(4),Padding=new Thickness(14,9),Background=new SolidColorBrush(Color.FromRgb(23,105,224)),Foreground=Brushes.White};b.Click+=click;return b;}
 void Show(string title,UIElement content){PageTitle.Text=title;ContentFrame.Content=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Padding=new Thickness(28),Content=content};}
 StackPanel Header(string title,string subtitle,params Button[] buttons){var h=new StackPanel();h.Children.Add(new TextBlock{Text=title,FontSize=28,FontWeight=FontWeights.Bold,Foreground=(Brush)FindResource("TextBrush")});h.Children.Add(new TextBlock{Text=subtitle,Foreground=(Brush)FindResource("MutedBrush"),Margin=new Thickness(0,3,0,15)});var bar=new StackPanel{Orientation=Orientation.Horizontal};foreach(var b in buttons)bar.Children.Add(b);h.Children.Add(bar);return h;}
 DataGrid Table(string sql,params (string,object)[] p){var d=svc.Query(sql,p);var t=new DataTable();foreach(var c in d.Columns)t.Columns.Add(c);foreach(var r in d.Rows)t.Rows.Add(r);return new DataGrid{ItemsSource=t.DefaultView,AutoGenerateColumns=true,IsReadOnly=true,Margin=new Thickness(0,12,0,0),CanUserAddRows=false,MinHeight=400,GridLinesVisibility=DataGridGridLinesVisibility.Horizontal,SelectionMode=DataGridSelectionMode.Single};}
 Border Card(string title,string value)=>new(){Background=Brushes.White,CornerRadius=new CornerRadius(12),Margin=new Thickness(5),Padding=new Thickness(18),Child=new StackPanel{Children={new TextBlock{Text=title,Foreground=(Brush)FindResource("MutedBrush")},new TextBlock{Text=value,FontSize=23,FontWeight=FontWeights.Bold,Foreground=(Brush)FindResource("TextBrush"),Margin=new Thickness(0,5,0,0)}}}};
 string Money(object? v)=>$"{Convert.ToDecimal(v??0):N2} MT"; decimal D(string s)=>decimal.Parse((s??"0").Replace(',','.'),System.Globalization.CultureInfo.InvariantCulture);void Error(Exception ex)=>MessageBox.Show(ex.Message,"AyGest",MessageBoxButton.OK,MessageBoxImage.Error);
 string[]? Form(string title,params (string label,string value)[] fields){var w=new Window{Title=title,Width=460,SizeToContent=SizeToContent.Height,Owner=this,WindowStartupLocation=WindowStartupLocation.CenterOwner};var p=new StackPanel{Margin=new Thickness(22)};var boxes=new List<TextBox>();foreach(var f in fields){p.Children.Add(new TextBlock{Text=f.label,Margin=new Thickness(4,7,4,2),FontWeight=FontWeights.SemiBold});var b=new TextBox{Text=f.value,Margin=new Thickness(4)};boxes.Add(b);p.Children.Add(b);}var ok=new Button{Content="Guardar",Margin=new Thickness(4,14,4,4),Padding=new Thickness(14,10)};ok.Click+=(_,_)=>w.DialogResult=true;p.Children.Add(ok);w.Content=p;if(w.ShowDialog()!=true)return null;return boxes.Select(x=>x.Text.Trim()).ToArray();}
 string Setting(string key,string fallback=""){var r=svc.Query("SELECT value FROM app_settings WHERE key=@k",("@k",key)).Rows.FirstOrDefault();return r is null?fallback:Convert.ToString(r[0])??fallback;}
 void SetSetting(string key,string value)=>svc.Execute("INSERT INTO app_settings(key,value) VALUES(@k,@v) ON CONFLICT(key) DO UPDATE SET value=excluded.value",("@k",key),("@v",value));
 static string DeviceId(){using var sha=SHA256.Create();return Convert.ToHexString(sha.ComputeHash(Encoding.UTF8.GetBytes(Environment.MachineName+"|"+Environment.UserName))).ToLowerInvariant();}
 void Dashboard_Click(object s,RoutedEventArgs e){var p=new StackPanel();p.Children.Add(Header("Dashboard","Resumo operacional da empresa",B("Actualizar",(_,_)=>Dashboard_Click(this,new()))));var t=svc.Query("SELECT COUNT(*),COALESCE(SUM(total),0),COALESCE(SUM(vat),0) FROM invoices WHERE company_id=@c AND status='issued' AND date(created_at)=date('now')",("@c",companyId));var r=t.Rows.FirstOrDefault();var cards=new UniformGrid{Columns=4,Margin=new Thickness(0,10,0,20)};cards.Children.Add(Card("Vendas hoje",Money(r?[1])));cards.Children.Add(Card("IVA hoje",Money(r?[2])));var st=svc.Query("SELECT COUNT(*) FROM products WHERE company_id=@c AND active=1",("@c",companyId));cards.Children.Add(Card("Produtos",Convert.ToString(st.Rows.FirstOrDefault()?[0])??"0"));var low=svc.Query("SELECT COUNT(*) FROM products p JOIN stock s ON s.product_id=p.id WHERE p.company_id=@c AND s.quantity<=p.min_stock",("@c",companyId));cards.Children.Add(Card("Stock crítico",Convert.ToString(low.Rows.FirstOrDefault()?[0])??"0"));p.Children.Add(cards);p.Children.Add(Table("SELECT number,status,subtotal,vat,total,payment_method,created_at FROM invoices WHERE company_id=@c ORDER BY id DESC LIMIT 15",("@c",companyId)));Show("Dashboard",p);}
 void Products_Click(object s,RoutedEventArgs e){var add=B("+ Novo produto",(_,_)=>AddProduct());var deactivate=B("Desactivar",(_,_)=>DeactivateProduct());var p=Header("Produtos","Catálogo, preços, IVA, SKU e stock mínimo",add,deactivate);grid=Table("SELECT p.id,p.name,p.sku,p.barcode,p.cost,p.price,p.vat_rate,p.min_stock,COALESCE(s.quantity,0) stock,p.active FROM products p LEFT JOIN stock s ON s.product_id=p.id WHERE p.company_id=@c ORDER BY p.name",("@c",companyId));p.Children.Add(grid);Show("Produtos",p);}
 void AddProduct(){var f=Form("Novo produto",("Nome",""),("SKU",""),("Código de barras",""),("Custo","0"),("Preço de venda","0"),("IVA %","16"),("Stock mínimo","0"));if(f==null)return;try{svc.AddProduct(companyId,f[0],f[1],f[2],D(f[3]),D(f[4]),D(f[5]),D(f[6]));Products_Click(this,new());}catch(Exception ex){Error(ex);}}
 void DeactivateProduct(){if(grid.SelectedItem is not DataRowView r)return;try{svc.Execute("UPDATE products SET active=0 WHERE id=@i AND company_id=@c",("@i",Convert.ToInt64(r["id"])),("@c",companyId));Products_Click(this,new());}catch(Exception ex){Error(ex);}}
 void Customers_Click(object s,RoutedEventArgs e){var add=B("+ Novo cliente",(_,_)=>AddCustomer());var p=Header("Clientes","Cadastro e histórico comercial",add);p.Children.Add(Table("SELECT id,name,nuit,phone,email,address FROM customers WHERE company_id=@c AND active=1 ORDER BY name",("@c",companyId)));Show("Clientes",p);}
 void AddCustomer(){var f=Form("Novo cliente",("Nome",""),("NUIT",""),("Telefone",""),("E-mail",""));if(f==null)return;try{svc.AddCustomer(companyId,f[0],f[1],f[2],f[3]);Customers_Click(this,new());}catch(Exception ex){Error(ex);}}
 void Suppliers_Click(object s,RoutedEventArgs e){var add=B("+ Novo fornecedor",(_,_)=>AddSupplier());var p=Header("Fornecedores","Cadastro e relacionamento de compras",add);p.Children.Add(Table("SELECT id,name,nuit,phone,email,address FROM suppliers WHERE company_id=@c ORDER BY name",("@c",companyId)));Show("Fornecedores",p);}
 void AddSupplier(){var f=Form("Novo fornecedor",("Nome",""),("NUIT",""),("Telefone",""),("E-mail",""));if(f==null)return;try{svc.AddSupplier(companyId,f[0],f[1],f[2],f[3]);Suppliers_Click(this,new());}catch(Exception ex){Error(ex);}}
 void Stock_Click(object s,RoutedEventArgs e){var adjust=B("Ajustar stock",(_,_)=>AdjustStock());var history=B("Movimentos",(_,_)=>StockMovements());var p=Header("Stock","Inventário, disponibilidade e movimentos",adjust,history);p.Children.Add(Table("SELECT p.id,p.name,p.sku,COALESCE(s.quantity,0) quantity,p.min_stock,(COALESCE(s.quantity,0)-p.min_stock) margin FROM products p LEFT JOIN stock s ON s.product_id=p.id WHERE p.company_id=@c AND p.active=1 ORDER BY p.name",("@c",companyId)));Show("Stock",p);}
 void AdjustStock(){var f=Form("Ajuste de stock",("ID do produto",""),("Quantidade (+/-)","0"),("Motivo","Ajuste manual"));if(f==null)return;try{var q=D(f[1]);var pid=long.Parse(f[0]);svc.Execute("UPDATE stock SET quantity=quantity+@q WHERE product_id=@p AND quantity+@q>=0",("@q",q),("@p",pid));svc.Execute("INSERT INTO stock_movements(product_id,type,quantity,reference,created_at) VALUES(@p,'ADJUST',@q,@r,@d)",("@p",pid),("@q",q),("@r",f[2]),("@d",DateTime.UtcNow.ToString("O")));Stock_Click(this,new());}catch(Exception ex){Error(ex);}}
 void StockMovements(){var p=Header("Movimentos de stock","Histórico de entradas, vendas e ajustes");p.Children.Add(Table("SELECT sm.id,p.name,sm.type,sm.quantity,sm.reference,sm.created_at FROM stock_movements sm JOIN products p ON p.id=sm.product_id WHERE p.company_id=@c ORDER BY sm.id DESC LIMIT 500",("@c",companyId)));Show("Movimentos de stock",p);}
 void Invoices_Click(object s,RoutedEventArgs e){var sell=B("+ Nova factura / POS",(_,_)=>NewInvoice());var cancel=B("Anular seleccionada",(_,_)=>CancelSelected());var pdf=B("PDF A4",(_,_)=>ExportSelectedInvoice());var p=Header("Facturação","Documentos, pagamentos, anulação, impressão e histórico",sell,cancel,pdf);grid=Table("SELECT id,number,status,subtotal,vat,total,payment_method,created_at FROM invoices WHERE company_id=@c ORDER BY id DESC",("@c",companyId));p.Children.Add(grid);Show("Facturação",p);}
 void CancelSelected(){if(grid.SelectedItem is not DataRowView row)return;var f=Form("Anular factura",("Motivo",""));if(f==null)return;try{svc.CancelInvoice(Convert.ToInt64(row["id"]),f[0]);Invoices_Click(this,new());}catch(Exception ex){Error(ex);}}
 void ExportSelectedInvoice(){if(grid.SelectedItem is not DataRowView row)return;try{var id=Convert.ToInt64(row["id"]);var h=svc.Query("SELECT i.number,i.payment_method,COALESCE(c.name,'Consumidor final'),co.name,co.nuit FROM invoices i JOIN companies co ON co.id=i.company_id LEFT JOIN customers c ON c.id=i.customer_id WHERE i.id=@i",("@i",id)).Rows.First();var items=svc.Query("SELECT description,quantity,unit_price,vat_rate FROM invoice_items WHERE invoice_id=@i",("@i",id));var lines=items.Rows.Select(x=>(Convert.ToString(x[0])??"",Convert.ToDecimal(x[1]),Convert.ToDecimal(x[2]),Convert.ToDecimal(x[3])));var path=new InvoicePdfService().Generate(System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"AyGest","Facturas"),Convert.ToString(h[3])??"",Convert.ToString(h[4])??"",Convert.ToString(h[0])??"",Convert.ToString(h[2])??"",Convert.ToString(h[1])??"",lines);System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(path){UseShellExecute=true});}catch(Exception ex){Error(ex);}}
 void NewInvoice(){var products=svc.Query("SELECT p.id,p.name,p.price,p.vat_rate,COALESCE(s.quantity,0) stock FROM products p JOIN stock s ON s.product_id=p.id WHERE p.company_id=@c AND p.active=1 ORDER BY p.name",("@c",companyId));if(products.Rows.Count==0){MessageBox.Show("Cadastre produtos e dê entrada de stock primeiro.","AyGest");return;}var w=new Window{Title="Nova factura / POS",Width=620,Height=560,Owner=this,WindowStartupLocation=WindowStartupLocation.CenterOwner};var sp=new StackPanel{Margin=new Thickness(22)};var combo=new ComboBox{Margin=new Thickness(4),DisplayMemberPath="Name"};foreach(var r in products.Rows)combo.Items.Add(new ProductChoice(Convert.ToInt64(r[0]),Convert.ToString(r[1])!,Convert.ToDecimal(r[2]),Convert.ToDecimal(r[3]),Convert.ToDecimal(r[4])));combo.SelectedIndex=0;var qty=new TextBox{Text="1",Margin=new Thickness(4)};var pay=new ComboBox{ItemsSource=new[]{"Dinheiro","Cartão","M-Pesa","E-Mola","Transferência"},Margin=new Thickness(4)};pay.SelectedIndex=0;var cust=new TextBox{Margin=new Thickness(4)};sp.Children.Add(new TextBlock{Text="Produto"});sp.Children.Add(combo);sp.Children.Add(new TextBlock{Text="Quantidade"});sp.Children.Add(qty);sp.Children.Add(new TextBlock{Text="ID cliente (opcional)"});sp.Children.Add(cust);sp.Children.Add(new TextBlock{Text="Pagamento"});sp.Children.Add(pay);sp.Children.Add(B("Emitir factura",(_,_)=>{try{var x=(ProductChoice)combo.SelectedItem;var id=svc.CreateInvoice(companyId,string.IsNullOrWhiteSpace(cust.Text)?null:long.Parse(cust.Text),new[]{(x.Id,x.Name,D(qty.Text),x.Price,x.Vat)},pay.Text);w.Close();MessageBox.Show($"Factura emitida. ID: {id}");Invoices_Click(this,new());}catch(Exception ex){Error(ex);}}));w.Content=sp;w.ShowDialog();}
 record ProductChoice(long Id,string Name,decimal Price,decimal Vat,decimal Stock);
 void Purchases_Click(object s,RoutedEventArgs e){var receive=B("+ Entrada de compra",(_,_)=>ReceivePurchase());var p=Header("Compras","Entradas de mercadoria e custos",receive);p.Children.Add(Table("SELECT number,status,total,vat,created_at FROM purchases WHERE company_id=@c ORDER BY id DESC",("@c",companyId)));Show("Compras",p);}
 void ReceivePurchase(){var f=Form("Entrada de compra",("ID produto",""),("Quantidade","1"),("Custo unitário","0"),("IVA %","16"),("Fornecedor ID",""));if(f==null)return;try{var pid=long.Parse(f[0]);var qty=D(f[1]);var cost=D(f[2]);var vat=D(f[3]);using var c=db.Open();using var tx=c.BeginTransaction();using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO purchases(company_id,supplier_id,number,total,vat,created_at) VALUES(@c,@s,@n,@t,@v,@d);SELECT last_insert_rowid()";q.Parameters.AddWithValue("@c",companyId);q.Parameters.AddWithValue("@s",string.IsNullOrWhiteSpace(f[4])?DBNull.Value:long.Parse(f[4]));q.Parameters.AddWithValue("@n",$"CP-{DateTime.Now:yyyyMMdd-HHmmss}");q.Parameters.AddWithValue("@t",qty*cost*(1+vat/100));q.Parameters.AddWithValue("@v",qty*cost*vat/100);q.Parameters.AddWithValue("@d",DateTime.UtcNow.ToString("O"));var id=Convert.ToInt64(q.ExecuteScalar());q.Parameters.Clear();q.CommandText="INSERT INTO purchase_items(purchase_id,product_id,quantity,unit_cost,line_total) VALUES(@i,@p,@q,@u,@t);UPDATE stock SET quantity=quantity+@q WHERE product_id=@p;INSERT INTO stock_movements(product_id,type,quantity,reference,created_at) VALUES(@p,'PURCHASE',@q,@r,@d)";q.Parameters.AddWithValue("@i",id);q.Parameters.AddWithValue("@p",pid);q.Parameters.AddWithValue("@q",qty);q.Parameters.AddWithValue("@u",cost);q.Parameters.AddWithValue("@t",qty*cost);q.Parameters.AddWithValue("@r",id);q.Parameters.AddWithValue("@d",DateTime.UtcNow.ToString("O"));q.ExecuteNonQuery();tx.Commit();Purchases_Click(this,new());}catch(Exception ex){Error(ex);}}
 void Cash_Click(object s,RoutedEventArgs e){var p=Header("Financeiro / Caixa","Abertura, movimentos, reconciliação e fecho",B("Abrir caixa",(_,_)=>OpenCash()),B("Movimento",(_,_)=>CashMove()),B("Fechar caixa",(_,_)=>CloseCash()));p.Children.Add(Table("SELECT id,status,opening_amount,expected_amount,closing_amount,opened_at,closed_at FROM cash_sessions WHERE company_id=@c ORDER BY id DESC",("@c",companyId)));Show("Financeiro / Caixa",p);}
 void OpenCash(){var f=Form("Abrir caixa",("Fundo inicial","0"));if(f==null)return;try{svc.OpenCash(companyId,D(f[0]));Cash_Click(this,new());}catch(Exception ex){Error(ex);}}
 long CurrentCash(){var r=svc.Query("SELECT id FROM cash_sessions WHERE company_id=@c AND status='open' LIMIT 1",("@c",companyId)).Rows.FirstOrDefault();return r is null?0:Convert.ToInt64(r[0]);}
 void CashMove(){var id=CurrentCash();if(id==0){MessageBox.Show("Abra primeiro o caixa.");return;}var f=Form("Movimento de caixa",("Tipo (IN/OUT)","IN"),("Descrição",""),("Valor","0"),("Método","Dinheiro"));if(f==null)return;try{var type=f[0].ToUpperInvariant();if(type!="IN"&&type!="OUT")throw new InvalidOperationException("Tipo deve ser IN ou OUT.");svc.CashMovement(id,type,f[1],D(f[2]),f[3]);Cash_Click(this,new());}catch(Exception ex){Error(ex);}}
 void CloseCash(){var id=CurrentCash();if(id==0){MessageBox.Show("Não há caixa aberto.");return;}var f=Form("Fechar caixa",("Valor contado","0"));if(f==null)return;try{svc.CloseCash(id,D(f[0]));Cash_Click(this,new());}catch(Exception ex){Error(ex);}}
 void Reports_Click(object s,RoutedEventArgs e){var export=B("Exportar CSV",(_,_)=>ExportReportCsv());var p=Header("Relatórios","Facturação, IVA, documentos, stock e desempenho",export);var t=svc.Query("SELECT COALESCE(SUM(total),0),COALESCE(SUM(vat),0),COUNT(*) FROM invoices WHERE company_id=@c AND status='issued'",("@c",companyId));var r=t.Rows.FirstOrDefault();var cards=new UniformGrid{Columns=3};cards.Children.Add(Card("Facturação",Money(r?[0])));cards.Children.Add(Card("IVA",Money(r?[1])));cards.Children.Add(Card("Documentos",Convert.ToString(r?[2])??"0"));p.Children.Add(cards);p.Children.Add(Table("SELECT p.name,p.sku,COALESCE(s.quantity,0) stock,p.min_stock,p.cost,p.price,(p.price-p.cost) margin FROM products p JOIN stock s ON s.product_id=p.id WHERE p.company_id=@c ORDER BY (s.quantity-p.min_stock)",("@c",companyId)));Show("Relatórios",p);}
 void ExportReportCsv(){var data=svc.Query("SELECT number,status,subtotal,vat,total,payment_method,created_at FROM invoices WHERE company_id=@c ORDER BY id DESC",("@c",companyId));var dlg=new SaveFileDialog{Filter="CSV (*.csv)|*.csv",FileName=$"AyGest-Relatorio-{DateTime.Now:yyyyMMdd-HHmm}.csv"};if(dlg.ShowDialog()!=true)return;var sb=new StringBuilder();sb.AppendLine(string.Join(";",data.Columns));foreach(var r in data.Rows)sb.AppendLine(string.Join(";",r.Select(x=>(x?.ToString()??"").Replace(";",","))));File.WriteAllText(dlg.FileName,sb.ToString(),Encoding.UTF8);MessageBox.Show("Relatório exportado.");}
 void Sales_Click(object s,RoutedEventArgs e)=>Invoices_Click(s,e);
 void Users_Click(object s,RoutedEventArgs e){var add=B("+ Novo utilizador",(_,_)=>AddUser());var p=Header("Utilizadores","Perfis e acesso ao sistema",add);p.Children.Add(Table("SELECT id,name,username,role,active FROM users WHERE company_id=@c ORDER BY name",("@c",companyId)));Show("Utilizadores",p);}
 void AddUser(){var f=Form("Novo utilizador",("Nome",""),("Username",""),("Password",""),("Perfil","Operator"));if(f==null)return;try{var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(f[2])));svc.Execute("INSERT INTO users(company_id,name,username,password_hash,role) VALUES(@c,@n,@u,@p,@r)",("@c",companyId),("@n",f[0]),("@u",f[1]),("@p",hash),("@r",f[3]));Users_Click(this,new());}catch(Exception ex){Error(ex);}}
 void Audit_Click(object s,RoutedEventArgs e){var p=Header("Auditoria","Histórico de operações do sistema");p.Children.Add(Table("SELECT action,entity,entity_id,details,created_at FROM audit_log WHERE company_id=@c ORDER BY id DESC LIMIT 500",("@c",companyId)));Show("Auditoria",p);}
 async void License_Click(object s,RoutedEventArgs e){var p=Header("Licenciamento","Activation Key online, tenant, plano e validade",B("Verificar licença",async(_,_)=>await VerifyLicense()));var key=new TextBox{Width=420,Padding=new Thickness(10),Margin=new Thickness(0,10,0,8),Text=Setting("license_key")};p.Children.Add(new TextBlock{Text="Activation Key",FontSize=16,FontWeight=FontWeights.Bold});p.Children.Add(key);p.Children.Add(B("Activar online",async(_,_)=>{try{var url=Setting("server_url",Environment.GetEnvironmentVariable("AYGEST_SERVER_URL")??"");if(string.IsNullOrWhiteSpace(url))throw new InvalidOperationException("Configure primeiro a URL do servidor em Configurações.");online?.Dispose();online=new OnlineApiClient(url);var result=await online.ActivateAsync(key.Text.Trim(),DeviceId(),Setting("tenant_id"));if(!result.Active)throw new InvalidOperationException(result.Message??"Licença recusada.");SetSetting("license_key",key.Text.Trim().ToUpperInvariant());if(!string.IsNullOrWhiteSpace(result.TenantId))SetSetting("tenant_id",result.TenantId!);SetSetting("license_plan",result.Plan??"");SetSetting("license_expires",result.ExpiresAt??"");StatusText.Text="Online • Licença activa";MessageBox.Show($"Licença activa. Tenant: {result.TenantId}\nPlano: {result.Plan}\nValidade: {result.ExpiresAt}");}catch(Exception ex){Error(ex);}}));p.Children.Add(new TextBlock{Text=$"Tenant: {Setting("tenant_id","—")}\nPlano: {Setting("license_plan","—")}\nExpira: {Setting("license_expires","—")}",Margin=new Thickness(4,15,4,4)});Show("Licenciamento",p);}
 async Task VerifyLicense(){try{var key=Setting("license_key");var url=Setting("server_url",Environment.GetEnvironmentVariable("AYGEST_SERVER_URL")??"");if(string.IsNullOrWhiteSpace(key)||string.IsNullOrWhiteSpace(url))throw new InvalidOperationException("Configure servidor e Activation Key.");online?.Dispose();online=new OnlineApiClient(url);var r=await online.VerifyAsync(key,DeviceId(),Setting("tenant_id"));StatusText.Text=r.Active?"Online • Licença válida":"Online • Licença inválida";MessageBox.Show(r.Message??(r.Active?"Licença válida.":"Licença inválida."));}catch(Exception ex){Error(ex);}}
 void Settings_Click(object s,RoutedEventArgs e){var save=B("Guardar",(_,_)=>{SetSetting("server_url",server.Text.Trim());SetSetting("company_name",name.Text.Trim());SetSetting("company_nuit",nuit.Text.Trim());MessageBox.Show("Configurações guardadas.");});var p=Header("Configurações","Empresa, servidor online e sistema",save);var name=new TextBox{Text=Setting("company_name","Minha Empresa"),Margin=new Thickness(4)};var nuit=new TextBox{Text=Setting("company_nuit",""),Margin=new Thickness(4)};var server=new TextBox{Text=Setting("server_url",Environment.GetEnvironmentVariable("AYGEST_SERVER_URL")??""),Margin=new Thickness(4)};p.Children.Add(new TextBlock{Text="Nome da empresa"});p.Children.Add(name);p.Children.Add(new TextBlock{Text="NUIT"});p.Children.Add(nuit);p.Children.Add(new TextBlock{Text="URL do servidor online"});p.Children.Add(server);p.Children.Add(new TextBlock{Text="Base de dados local: "+db.Path,Margin=new Thickness(4,15,4,4),Foreground=(Brush)FindResource("MutedBrush")});Show("Configurações",p);}
}