using System.Data;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using AyGest.Wpf.Services;

namespace AyGest.Wpf;
public partial class MainWindow : Window
{
 readonly Data.AppDb db=new(); readonly BusinessService svc; readonly long companyId; DataGrid grid=new();
 public MainWindow(){InitializeComponent();svc=new BusinessService(db);companyId=svc.EnsureCompany();Dashboard_Click(this,new RoutedEventArgs());}
 Button B(string text,RoutedEventHandler click){var b=new Button{Content=text,Margin=new Thickness(4),Padding=new Thickness(14,9),Background=new SolidColorBrush(Color.FromRgb(23,105,224)),Foreground=Brushes.White};b.Click+=click;return b;}
 void Show(string title,UIElement content){PageTitle.Text=title;var s=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Padding=new Thickness(28),Content=content};ContentFrame.Content=s;}
 StackPanel Header(string title,string subtitle,params Button[] buttons){var h=new StackPanel();h.Children.Add(new TextBlock{Text=title,FontSize=28,FontWeight=FontWeights.Bold,Foreground=(Brush)FindResource("TextBrush")});h.Children.Add(new TextBlock{Text=subtitle,Foreground=(Brush)FindResource("MutedBrush"),Margin=new Thickness(0,3,0,15)});var bar=new StackPanel{Orientation=Orientation.Horizontal};foreach(var b in buttons)bar.Children.Add(b);h.Children.Add(bar);return h;}
 DataGrid Table(string sql,params (string,object)[] p){var d=svc.Query(sql,p);var t=new DataTable();foreach(var c in d.Columns)t.Columns.Add(c);foreach(var r in d.Rows)t.Rows.Add(r);return new DataGrid{ItemsSource=t.DefaultView,AutoGenerateColumns=true,IsReadOnly=true,Margin=new Thickness(0,12,0,0),CanUserAddRows=false,MinHeight=400,GridLinesVisibility=DataGridGridLinesVisibility.Horizontal};}
 void Dashboard_Click(object s,RoutedEventArgs e){var p=new StackPanel();p.Children.Add(Header("Dashboard","Resumo operacional da empresa"));var t=svc.Query("SELECT COUNT(*) n,COALESCE(SUM(total),0) total,COALESCE(SUM(vat),0) vat FROM invoices WHERE company_id=@c AND status='issued' AND date(created_at)=date('now')",("@c",companyId));var r=t.Rows.FirstOrDefault();var cards=new UniformGrid{Columns=4,Margin=new Thickness(0,10,0,20)};cards.Children.Add(Card("Vendas hoje",Money(r?[1])));cards.Children.Add(Card("IVA",Money(r?[2])));var st=svc.Query("SELECT COUNT(*) FROM products WHERE company_id=@c AND active=1",("@c",companyId));cards.Children.Add(Card("Produtos",Convert.ToString(st.Rows.FirstOrDefault()?[0])??"0"));var low=svc.Query("SELECT COUNT(*) FROM products p JOIN stock s ON s.product_id=p.id WHERE p.company_id=@c AND s.quantity<=p.min_stock",("@c",companyId));cards.Children.Add(Card("Stock crítico",Convert.ToString(low.Rows.FirstOrDefault()?[0])??"0"));p.Children.Add(cards);p.Children.Add(Table("SELECT number,status,subtotal,vat,total,payment_method,created_at FROM invoices WHERE company_id=@c ORDER BY id DESC LIMIT 15",("@c",companyId)));Show("Dashboard",p);}
 Border Card(string title,string value)=>new(){Background=Brushes.White,CornerRadius=new CornerRadius(12),Margin=new Thickness(5),Padding=new Thickness(18),Child=new StackPanel{Children={new TextBlock{Text=title,Foreground=(Brush)FindResource("MutedBrush")},new TextBlock{Text=value,FontSize=23,FontWeight=FontWeights.Bold,Foreground=(Brush)FindResource("TextBrush"),Margin=new Thickness(0,5,0,0)}}}};
 string Money(object? v)=>$"{Convert.ToDecimal(v??0):N2} MT";
 void Products_Click(object s,RoutedEventArgs e){var add=B("+ Novo produto",(_,_)=>AddProduct());var p=Header("Produtos","Catálogo, preços, IVA, SKU e stock mínimo",add);p.Children.Add(Table("SELECT p.id,p.name,p.sku,p.barcode,p.cost,p.price,p.vat_rate,p.min_stock,COALESCE(s.quantity,0) stock FROM products p LEFT JOIN stock s ON s.product_id=p.id WHERE p.company_id=@c ORDER BY p.name",("@c",companyId)));Show("Produtos",p);}
 void AddProduct(){var f=Form("Novo produto",("Nome", ""),("SKU", ""),("Código de barras", ""),("Custo", "0"),("Preço de venda", "0"),("IVA %", "16"),("Stock mínimo", "0"));if(f==null)return;try{svc.AddProduct(companyId,f[0],f[1],f[2],D(f[3]),D(f[4]),D(f[5]),D(f[6]));Products_Click(this,new());}catch(Exception ex){Error(ex);}}
 void Customers_Click(object s,RoutedEventArgs e){var add=B("+ Novo cliente",(_,_)=>AddCustomer());var p=Header("Clientes","Cadastro e histórico comercial",add);p.Children.Add(Table("SELECT id,name,nuit,phone,email,address FROM customers WHERE company_id=@c ORDER BY name",("@c",companyId)));Show("Clientes",p);}
 void AddCustomer(){var f=Form("Novo cliente",("Nome",""),("NUIT",""),("Telefone",""),("E-mail",""));if(f==null)return;try{svc.AddCustomer(companyId,f[0],f[1],f[2],f[3]);Customers_Click(this,new());}catch(Exception ex){Error(ex);}}
 void Suppliers_Click(object s,RoutedEventArgs e){var add=B("+ Novo fornecedor",(_,_)=>AddSupplier());var p=Header("Fornecedores","Cadastro e relacionamento de compras",add);p.Children.Add(Table("SELECT id,name,nuit,phone,email,address FROM suppliers WHERE company_id=@c ORDER BY name",("@c",companyId)));Show("Fornecedores",p);}
 void AddSupplier(){var f=Form("Novo fornecedor",("Nome",""),("NUIT",""),("Telefone",""),("E-mail",""));if(f==null)return;try{svc.AddSupplier(companyId,f[0],f[1],f[2],f[3]);Suppliers_Click(this,new());}catch(Exception ex){Error(ex);}}
 void Stock_Click(object s,RoutedEventArgs e){var adjust=B("Ajustar stock",(_,_)=>AdjustStock());var p=Header("Stock","Inventário, disponibilidade e movimentos",adjust);p.Children.Add(Table("SELECT p.id,p.name,p.sku,COALESCE(s.quantity,0) quantity,p.min_stock,(COALESCE(s.quantity,0)-p.min_stock) margin FROM products p LEFT JOIN stock s ON s.product_id=p.id WHERE p.company_id=@c ORDER BY p.name",("@c",companyId)));Show("Stock",p);}
 void AdjustStock(){var f=Form("Ajuste de stock",("ID do produto",""),("Quantidade (+/-)","0"),("Motivo","Ajuste manual"));if(f==null)return;try{var q=D(f[1]);svc.Execute("UPDATE stock SET quantity=quantity+@q WHERE product_id=@p",("@q",q),("@p",long.Parse(f[0])));svc.Execute("INSERT INTO stock_movements(product_id,type,quantity,reference,created_at) VALUES(@p,'ADJUST',@q,@r,@d)",("@p",long.Parse(f[0])),("@q",q),("@r",f[2]),("@d",DateTime.UtcNow.ToString("O")));Stock_Click(this,new());}catch(Exception ex){Error(ex);}}
 void Invoices_Click(object s,RoutedEventArgs e){var sell=B("+ Nova factura",(_,_)=>NewInvoice());var cancel=B("Anular seleccionada",(_,_)=>CancelSelected());var p=Header("Facturação","Documentos, pagamentos, anulação e histórico",sell,cancel);grid=Table("SELECT id,number,status,subtotal,vat,total,payment_method,created_at FROM invoices WHERE company_id=@c ORDER BY id DESC",("@c",companyId));p.Children.Add(grid);Show("Facturação",p);}
 void CancelSelected(){if(grid.SelectedItem is not DataRowView row)return;var id=Convert.ToInt64(row["id"]);var f=Form("Anular factura",("Motivo",""));if(f==null)return;try{svc.CancelInvoice(id,f[0]);Invoices_Click(this,new());}catch(Exception ex){Error(ex);}}
 void NewInvoice(){var products=svc.Query("SELECT p.id,p.name,p.price,p.vat_rate,COALESCE(s.quantity,0) stock FROM products p JOIN stock s ON s.product_id=p.id WHERE p.company_id=@c AND p.active=1 ORDER BY p.name",("@c",companyId));if(products.Rows.Count==0){MessageBox.Show("Cadastre produtos e dê entrada de stock primeiro.","AyGest",MessageBoxButton.OK,MessageBoxImage.Information);return;}var w=new Window{Title="Nova factura / POS",Width=520,Height=500,Owner=this,WindowStartupLocation=WindowStartupLocation.CenterOwner};var sp=new StackPanel{Margin=new Thickness(22)};var combo=new ComboBox{Margin=new Thickness(4),DisplayMemberPath="Name"};foreach(var r in products.Rows)combo.Items.Add(new ProductChoice(Convert.ToInt64(r[0]),Convert.ToString(r[1])!,Convert.ToDecimal(r[2]),Convert.ToDecimal(r[3]),Convert.ToDecimal(r[4])));combo.SelectedIndex=0;var qty=new TextBox{Text="1",Margin=new Thickness(4)};var pay=new ComboBox{ItemsSource=new[]{"Dinheiro","Cartão","M-Pesa","E-Mola","Transferência"},Margin=new Thickness(4)};pay.SelectedIndex=0;var cust=new TextBox{Text="",Margin=new Thickness(4)};sp.Children.Add(new TextBlock{Text="Produto"});sp.Children.Add(combo);sp.Children.Add(new TextBlock{Text="Quantidade"});sp.Children.Add(qty);sp.Children.Add(new TextBlock{Text="ID cliente (opcional)"});sp.Children.Add(cust);sp.Children.Add(new TextBlock{Text="Pagamento"});sp.Children.Add(pay);var ok=B("Emitir factura",(_,_)=>{try{var x=(ProductChoice)combo.SelectedItem;var id=svc.CreateInvoice(companyId,string.IsNullOrWhiteSpace(cust.Text)?null:long.Parse(cust.Text),new[]{(x.Id,x.Name,D(qty.Text),x.Price,x.Vat)},pay.Text);w.DialogResult=true;w.Close();MessageBox.Show($"Factura emitida com sucesso.\nID: {id}","AyGest",MessageBoxButton.OK,MessageBoxImage.Information);Invoices_Click(this,new());}catch(Exception ex){Error(ex);}});sp.Children.Add(ok);w.Content=sp;w.ShowDialog();}
 record ProductChoice(long Id,string Name,decimal Price,decimal Vat,decimal Stock);
 void Purchases_Click(object s,RoutedEventArgs e){var receive=B("+ Entrada de compra",(_,_)=>ReceivePurchase());var p=Header("Compras","Entradas de mercadoria e custos",receive);p.Children.Add(Table("SELECT number,status,total,vat,created_at FROM purchases WHERE company_id=@c ORDER BY id DESC",("@c",companyId)));Show("Compras",p);}
 void ReceivePurchase(){var f=Form("Entrada de compra",("ID produto",""),("Quantidade","1"),("Custo unitário","0"),("IVA %","16"),("Fornecedor ID",""));if(f==null)return;try{var pid=long.Parse(f[0]);var qty=D(f[1]);var cost=D(f[2]);var vat=D(f[3]);var total=qty*cost;using var c=db.Open();using var tx=c.BeginTransaction();using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO purchases(company_id,supplier_id,number,total,vat,created_at) VALUES(@c,@s,@n,@t,@v,@d);SELECT last_insert_rowid()";q.Parameters.AddWithValue("@c",companyId);q.Parameters.AddWithValue("@s",string.IsNullOrWhiteSpace(f[4])?DBNull.Value:long.Parse(f[4]));q.Parameters.AddWithValue("@n",$"CP-{DateTime.Now:yyyy}-{DateTime.Now:HHmmss}");q.Parameters.AddWithValue("@t",total+total*vat/100);q.Parameters.AddWithValue("@v",total*vat/100);q.Parameters.AddWithValue("@d",DateTime.UtcNow.ToString("O"));var id=Convert.ToInt64(q.ExecuteScalar());q.Parameters.Clear();q.CommandText="INSERT INTO purchase_items(purchase_id,product_id,quantity,unit_cost,line_total) VALUES(@i,@p,@q,@u,@t);UPDATE stock SET quantity=quantity+@q WHERE product_id=@p;INSERT INTO stock_movements(product_id,type,quantity,reference,created_at) VALUES(@p,'PURCHASE',@q,@r,@d)";q.Parameters.AddWithValue("@i",id);q.Parameters.AddWithValue("@p",pid);q.Parameters.AddWithValue("@q",qty);q.Parameters.AddWithValue("@u",cost);q.Parameters.AddWithValue("@t",total);q.Parameters.AddWithValue("@r",id);q.Parameters.AddWithValue("@d",DateTime.UtcNow.ToString("O"));q.ExecuteNonQuery();tx.Commit();Purchases_Click(this,new());}catch(Exception ex){Error(ex);}}
 void Cash_Click(object s,RoutedEventArgs e){var open=B("Abrir caixa",(_,_)=>OpenCash());var mov=B("Movimento",(_,_)=>CashMove());var close=B("Fechar caixa",(_,_)=>CloseCash());var p=Header("Financeiro / Caixa","Abertura, movimentos e fecho",open,mov,close);p.Children.Add(Table("SELECT id,status,opening_amount,expected_amount,closing_amount,opened_at,closed_at FROM cash_sessions WHERE company_id=@c ORDER BY id DESC",("@c",companyId)));Show("Financeiro / Caixa",p);}
 void OpenCash(){var f=Form("Abrir caixa",("Fundo inicial","0"));if(f==null)return;try{svc.OpenCash(companyId,D(f[0]));Cash_Click(this,new());}catch(Exception ex){Error(ex);}}
 long CurrentCash(){var r=svc.Query("SELECT id FROM cash_sessions WHERE company_id=@c AND status='open' LIMIT 1",("@c",companyId)).Rows.FirstOrDefault();return r is null?0:Convert.ToInt64(r[0]);}
 void CashMove(){var id=CurrentCash();if(id==0){MessageBox.Show("Abra primeiro o caixa.");return;}var f=Form("Movimento de caixa",("Tipo (IN/OUT)","IN"),("Descrição",""),("Valor","0"),("Método","Dinheiro"));if(f==null)return;try{svc.CashMovement(id,f[0].ToUpperInvariant(),f[1],D(f[2]),f[3]);Cash_Click(this,new());}catch(Exception ex){Error(ex);}}
 void CloseCash(){var id=CurrentCash();if(id==0){MessageBox.Show("Não há caixa aberto.");return;}var f=Form("Fechar caixa",("Valor contado","0"));if(f==null)return;try{svc.CloseCash(id,D(f[0]));Cash_Click(this,new());}catch(Exception ex){Error(ex);}}
 void Reports_Click(object s,RoutedEventArgs e){var p=Header("Relatórios","Indicadores comerciais e operacionais");var t=svc.Query("SELECT COALESCE(SUM(total),0),COALESCE(SUM(vat),0),COUNT(*) FROM invoices WHERE company_id=@c AND status='issued'",("@c",companyId));var r=t.Rows.FirstOrDefault();var cards=new UniformGrid{Columns=3};cards.Children.Add(Card("Facturação",Money(r?[0])));cards.Children.Add(Card("IVA",Money(r?[1])));cards.Children.Add(Card("Documentos",Convert.ToString(r?[2])??"0"));p.Children.Add(cards);p.Children.Add(Table("SELECT p.name,p.sku,COALESCE(s.quantity,0) stock,p.min_stock,p.cost,p.price FROM products p JOIN stock s ON s.product_id=p.id WHERE p.company_id=@c ORDER BY (s.quantity-p.min_stock)",("@c",companyId)));Show("Relatórios",p);}
 void Sales_Click(object s,RoutedEventArgs e)=>Invoices_Click(s,e);
 void Users_Click(object s,RoutedEventArgs e){var p=Header("Utilizadores","Perfis e acesso ao sistema");p.Children.Add(Table("SELECT id,name,username,role,active FROM users WHERE company_id=@c ORDER BY name",("@c",companyId)));Show("Utilizadores",p);}
 void Audit_Click(object s,RoutedEventArgs e){var p=Header("Auditoria","Histórico de operações");p.Children.Add(Table("SELECT action,entity,entity_id,details,created_at FROM audit_log WHERE company_id=@c ORDER BY id DESC LIMIT 300",("@c",companyId)));Show("Auditoria",p);}
 void License_Click(object s,RoutedEventArgs e){var p=Header("Licenciamento","Activação e estado da licença");var key=new TextBox{Width=420,Padding=new Thickness(10),Margin=new Thickness(0,10,0,8)};var btn=B("Activar chave",(_,_)=>{if(string.IsNullOrWhiteSpace(key.Text)){MessageBox.Show("Introduza a Activation Key.");return;}svc.Execute("INSERT INTO licenses(company_id,key_value,plan,active) VALUES(@c,@k,'Standard',1) ON CONFLICT(key_value) DO UPDATE SET active=1",("@c",companyId),("@k",key.Text.Trim().ToUpperInvariant()));MessageBox.Show("Chave registada localmente. A validação online será ligada ao servidor de licenciamento.");});p.Children.Add(new TextBlock{Text="Activation Key",FontSize=16,FontWeight=FontWeights.Bold});p.Children.Add(key);p.Children.Add(btn);p.Children.Add(Table("SELECT key_value,plan,active,expires_at FROM licenses WHERE company_id=@c ORDER BY id DESC",("@c",companyId)));Show("Licenciamento",p);}
 void Settings_Click(object s,RoutedEventArgs e){var f=Form("Dados da empresa",("Nome","Minha Empresa"),("NUIT",""),("Telefone",""),("E-mail",""));if(f==null)return;svc.Execute("UPDATE companies SET name=@n,nuit=@u,phone=@p,email=@e WHERE id=@c",("@n",f[0]),("@u",f[1]),("@p",f[2]),("@e",f[3]),("@c",companyId));MessageBox.Show("Configuração guardada.");}
 Dictionary<string,string>? Form(string title,params (string,string)[] fields){var w=new Window{Title=title,Width=450,SizeToContent=SizeToContent.Height,Owner=this,WindowStartupLocation=WindowStartupLocation.CenterOwner};var sp=new StackPanel{Margin=new Thickness(20)};var boxes=new List<TextBox>();foreach(var f in fields){sp.Children.Add(new TextBlock{Text=f.Item1,Margin=new Thickness(4,8,4,2)});var b=new TextBox{Text=f.Item2,Padding=new Thickness(9),Margin=new Thickness(4)};boxes.Add(b);sp.Children.Add(b);}var panel=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};Dictionary<string,string>? result=null;var ok=B("Guardar",(_,_)=>{result=fields.Select((f,i)=>(f.Item1,boxes[i].Text)).ToDictionary(x=>x.Item1,x=>x.Item2);w.DialogResult=true;w.Close();});var cancel=new Button{Content="Cancelar",Margin=new Thickness(4),Padding=new Thickness(14,9)};cancel.Click+=(_,_)=>w.Close();panel.Children.Add(cancel);panel.Children.Add(ok);sp.Children.Add(panel);w.Content=sp;w.ShowDialog();return result is null?null:fields.Select((f,i)=>(f.Item1,boxes[i].Text)).ToDictionary(x=>x.Item1,x=>x.Item2);}
 decimal D(string s)=>decimal.Parse(s.Replace(',','.'),System.Globalization.CultureInfo.InvariantCulture);void Error(Exception ex)=>MessageBox.Show(ex.Message,"AyGest",MessageBoxButton.OK,MessageBoxImage.Error);
}
