using Microsoft.Data.Sqlite;using System.Collections.ObjectModel;using System.Text;using System.Windows;using System.Windows.Controls;using System.IO;
namespace AyGest.Wpf;
public partial class ProductsStockWindow:Window{
 readonly string _db=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AyGest","aygest.db");readonly ObservableCollection<ProductEditorWindow.ProductRow> _all=new();
 public ProductsStockWindow(){InitializeComponent();Directory.CreateDirectory(Path.GetDirectoryName(_db)!);EnsureSchema();ProductsGrid.ItemsSource=_all;Load();}
 SqliteConnection C()=>new($"Data Source={_db}");
 void EnsureSchema(){using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,sku TEXT NOT NULL UNIQUE,barcode TEXT,name TEXT NOT NULL,category TEXT,unit TEXT NOT NULL DEFAULT 'UN',sale_price REAL NOT NULL DEFAULT 0,cost_price REAL NOT NULL DEFAULT 0,stock REAL NOT NULL DEFAULT 0,min_stock REAL NOT NULL DEFAULT 0,max_stock REAL NOT NULL DEFAULT 0,vat REAL NOT NULL DEFAULT 16,location TEXT,supplier TEXT,brand TEXT,model TEXT,description TEXT,status TEXT NOT NULL DEFAULT 'Activo',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS stock_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER NOT NULL,type TEXT NOT NULL,quantity REAL NOT NULL,unit_cost REAL NOT NULL DEFAULT 0,reference TEXT,notes TEXT,created_at TEXT NOT NULL);";q.ExecuteNonQuery();}
 void Load(){_all.Clear();using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="SELECT id,sku,COALESCE(barcode,''),name,COALESCE(category,''),unit,sale_price,cost_price,stock,min_stock,max_stock,vat,COALESCE(location,''),COALESCE(supplier,''),COALESCE(brand,''),COALESCE(model,''),COALESCE(description,''),status FROM products ORDER BY category,name,sku";using var r=q.ExecuteReader();while(r.Read())_all.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetDecimal(6),r.GetDecimal(7),r.GetDecimal(8),r.GetDecimal(9),r.GetDecimal(10),r.GetDecimal(11),r.GetString(12),r.GetString(13),r.GetString(14),r.GetString(15),r.GetString(16),r.GetString(17)));PopulateCategories();Apply();}
 void PopulateCategories(){var existing=CategoryBox.Items.OfType<ComboBoxItem>().Select(x=>x.Content?.ToString()).ToHashSet();foreach(var cat in _all.Select(x=>x.Category).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct().OrderBy(x=>x))if(!existing.Contains(cat))CategoryBox.Items.Add(new ComboBoxItem{Content=cat});}
 void Apply(){var t=(SearchBox.Text??"").Trim().ToLowerInvariant();var cat=(CategoryBox.SelectedItem as ComboBoxItem)?.Content?.ToString();var stock=(StockBox.SelectedItem as ComboBoxItem)?.Content?.ToString();var st=(StatusBox.SelectedItem as ComboBoxItem)?.Content?.ToString();var list=_all.Where(x=>(t==""||$"{x.Sku} {x.Barcode} {x.Name} {x.Category} {x.Brand}".ToLowerInvariant().Contains(t))&&(cat=="Todas categorias"||cat==null||x.Category==cat)&&(stock=="Todo stock"||stock==null||(stock=="Stock baixo"&&x.Stock<=x.MinStock&&x.Stock>0)||(stock=="Sem stock"&&x.Stock<=0))&&(st=="Todos estados"||st==null||(st=="Activos"&&x.Status=="Activo")||(st=="Inactivos"&&x.Status!="Activo"))).ToList();ProductsGrid.ItemsSource=list;CountText.Content=list.Count.ToString();UnitsText.Content=list.Sum(x=>x.Stock).ToString("N2");ValueText.Content=list.Sum(x=>x.Stock*x.CostPrice).ToString("N2")+" MT";LowText.Content=list.Count(x=>x.Stock<=x.MinStock).ToString();}
 void FilterChanged(object s,EventArgs e)=>Apply();void Refresh_Click(object s,RoutedEventArgs e)=>Load();
 void New_Click(object s,RoutedEventArgs e){var d=new ProductEditorWindow{Owner=this};if(d.ShowDialog()==true){Save(d,null);Load();}}
 void Edit_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is not ProductEditorWindow.ProductRow x)return;var d=new ProductEditorWindow(x){Owner=this};if(d.ShowDialog()==true){Save(d,x.Id);Load();}}
 void Save(ProductEditorWindow d,long? id){using var c=C();c.Open();using var tx=c.BeginTransaction();using var q=c.CreateCommand();q.Transaction=tx;q.CommandText=id==null?"INSERT INTO products(sku,barcode,name,category,unit,sale_price,cost_price,stock,min_stock,max_stock,vat,location,supplier,brand,model,description,status,created_at,updated_at) VALUES($sku,$bar,$n,$cat,$u,$sp,$cp,$stock,$min,$max,$vat,$loc,$sup,$brand,$model,$desc,$status,$date,$date)":"UPDATE products SET barcode=$bar,name=$n,category=$cat,unit=$u,sale_price=$sp,cost_price=$cp,min_stock=$min,max_stock=$max,vat=$vat,location=$loc,supplier=$sup,brand=$brand,model=$model,description=$desc,status=$status,updated_at=$date WHERE id=$id";if(id!=null)q.Parameters.AddWithValue("$id",id);q.Parameters.AddWithValue("$sku",string.IsNullOrWhiteSpace(d.Sku)?"PRD"+DateTime.Now.ToString("yyyyMMddHHmmss"):d.Sku);q.Parameters.AddWithValue("$bar",d.Barcode);q.Parameters.AddWithValue("$n",d.Name);q.Parameters.AddWithValue("$cat",d.Category);q.Parameters.AddWithValue("$u",d.Unit);q.Parameters.AddWithValue("$sp",D(d.SalePrice));q.Parameters.AddWithValue("$cp",D(d.CostPrice));q.Parameters.AddWithValue("$stock",id==null?D(d.InitialStock):0);q.Parameters.AddWithValue("$min",D(d.MinStock));q.Parameters.AddWithValue("$max",D(d.MaxStock));q.Parameters.AddWithValue("$vat",D(d.Vat));q.Parameters.AddWithValue("$loc",d.Location);q.Parameters.AddWithValue("$sup",d.Supplier);q.Parameters.AddWithValue("$brand",d.Brand);q.Parameters.AddWithValue("$model",d.Model);q.Parameters.AddWithValue("$desc",d.Description);q.Parameters.AddWithValue("$status",d.Active?"Activo":"Inactivo");q.Parameters.AddWithValue("$date",DateTime.UtcNow.ToString("O"));q.ExecuteNonQuery();tx.Commit();}
 static decimal D(string x)=>decimal.TryParse(x.Replace(".",","),out var v)?v:0;
 void Stock_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is not ProductEditorWindow.ProductRow x)return;var qty=Microsoft.VisualBasic.Interaction.InputBox($"Quantidade para movimentar {x.Name}:","Movimento de stock","1");if(!decimal.TryParse(qty.Replace(".",","),out var n)||n<=0)return;Move(x.Id,n,"Entrada","Ajuste manual");Load();}
 void Entry_Click(object s,RoutedEventArgs e){StockDialog("Entrada");}void Exit_Click(object s,RoutedEventArgs e){StockDialog("Saída");}void Adjust_Click(object s,RoutedEventArgs e){StockDialog("Ajuste");}
 void StockDialog(string type){var sku=Microsoft.VisualBasic.Interaction.InputBox("SKU do produto:",type," ").Trim();var p=_all.FirstOrDefault(x=>x.Sku.Equals(sku,StringComparison.OrdinalIgnoreCase));if(p==null){MessageBox.Show("Produto não encontrado.");return;}var qty=Microsoft.VisualBasic.Interaction.InputBox("Quantidade:",type,"1");if(!decimal.TryParse(qty.Replace(".",","),out var n)||n<=0)return;if(type=="Saída"&&n>p.Stock){MessageBox.Show("Stock insuficiente.","Stock",MessageBoxButton.OK,MessageBoxImage.Warning);return;}Move(p.Id,type=="Saída"?-n:n,type,"Operação manual");Load();}
 void Move(long id,decimal qty,string type,string note){using var c=C();c.Open();using var tx=c.BeginTransaction();using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="UPDATE products SET stock=stock+$q,updated_at=$d WHERE id=$id AND stock+$q>=0";q.Parameters.AddWithValue("$q",qty);q.Parameters.AddWithValue("$id",id);q.Parameters.AddWithValue("$d",DateTime.UtcNow.ToString("O"));if(q.ExecuteNonQuery()!=1){tx.Rollback();MessageBox.Show("Operação recusada: stock insuficiente.");return;}using var m=c.CreateCommand();m.Transaction=tx;m.CommandText="INSERT INTO stock_movements(product_id,type,quantity,reference,notes,created_at) VALUES($id,$t,$q,$ref,$n,$d)";m.Parameters.AddWithValue("$id",id);m.Parameters.AddWithValue("$t",type);m.Parameters.AddWithValue("$q",qty);m.Parameters.AddWithValue("$ref","MANUAL");m.Parameters.AddWithValue("$n",note);m.Parameters.AddWithValue("$d",DateTime.UtcNow.ToString("O"));m.ExecuteNonQuery();tx.Commit();}
 void History_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is not ProductEditorWindow.ProductRow x)return;using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="SELECT type,quantity,COALESCE(reference,''),created_at FROM stock_movements WHERE product_id=$id ORDER BY id DESC LIMIT 30";q.Parameters.AddWithValue("$id",x.Id);using var r=q.ExecuteReader();var sb=new StringBuilder($"Histórico de stock — {x.Name}\n\n");while(r.Read())sb.AppendLine($"{r.GetString(0),-10} {r.GetDecimal(1),10:N2} {r.GetString(2),-12} {r.GetString(3)}");MessageBox.Show(sb.ToString(),"Histórico",MessageBoxButton.OK,MessageBoxImage.Information);}
 void More_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is not ProductEditorWindow.ProductRow x)return;if(MessageBox.Show($"Alterar estado de {x.Name}?","Produto",MessageBoxButton.YesNo,MessageBoxImage.Question)!=MessageBoxResult.Yes)return;using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="UPDATE products SET status=CASE WHEN status='Activo' THEN 'Inactivo' ELSE 'Activo' END WHERE id=$id";q.Parameters.AddWithValue("$id",x.Id);q.ExecuteNonQuery();Load();}
 void Export_Click(object s,RoutedEventArgs e){var sb=new StringBuilder("SKU;Código de barras;Produto;Categoria;Unidade;Preço;Custo;Stock;Mínimo;IVA;Estado\n");foreach(var x in _all)sb.AppendLine($"{x.Sku};{x.Barcode};{x.Name};{x.Category};{x.Unit};{x.SalePrice:N2};{x.CostPrice:N2};{x.Stock:N2};{x.MinStock:N2};{x.Vat:N2};{x.Status}");var p=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"AyGest_Produtos.csv");File.WriteAllText(p,sb.ToString(),Encoding.UTF8);MessageBox.Show("Exportação concluída:\n"+p,"Produtos",MessageBoxButton.OK,MessageBoxImage.Information);}
}
