using System.Windows;using System.Windows.Controls;
namespace AyGest.Wpf;
public partial class ProductEditorWindow:Window{
 public string Sku=>SkuBox.Text.Trim();public string Barcode=>BarcodeBox.Text.Trim();public string Name=>NameBox.Text.Trim();public string Category=>CategoryBox.Text.Trim();public string Unit=>(UnitBox.SelectedItem as ComboBoxItem)?.Content?.ToString()??"UN";public string SalePrice=>SalePriceBox.Text.Trim();public string CostPrice=>CostPriceBox.Text.Trim();public string MinStock=>MinStockBox.Text.Trim();public string MaxStock=>MaxStockBox.Text.Trim();public string Vat=>VatBox.Text.Trim();public string Location=>LocationBox.Text.Trim();public string InitialStock=>InitialStockBox.Text.Trim();public string Supplier=>SupplierBox.Text.Trim();public string Brand=>BrandBox.Text.Trim();public string Model=>ModelBox.Text.Trim();public string Description=>DescriptionBox.Text.Trim();public bool Active=>ActiveBox.IsChecked==true;
 public ProductEditorWindow(){InitializeComponent();}
 public ProductEditorWindow(ProductRow x):this(){SkuBox.Text=x.Sku;SkuBox.IsEnabled=false;NameBox.Text=x.Name;CategoryBox.Text=x.Category;SalePriceBox.Text=x.SalePrice.ToString("N2");CostPriceBox.Text=x.CostPrice.ToString("N2");MinStockBox.Text=x.MinStock.ToString("N2");UnitBox.SelectedIndex=Math.Max(0,UnitBox.Items.OfType<ComboBoxItem>().ToList().FindIndex(i=>i.Content?.ToString()==x.Unit));VatBox.Text=x.Vat.ToString("N2");ActiveBox.IsChecked=x.Status=="Activo";}
 void Save_Click(object s,RoutedEventArgs e){if(string.IsNullOrWhiteSpace(Name)){MessageBox.Show("O nome do produto é obrigatório.","Validação",MessageBoxButton.OK,MessageBoxImage.Warning);return;}if(!decimal.TryParse(SalePrice.Replace(".",","),out _)||!decimal.TryParse(CostPrice.Replace(".",","),out _)){MessageBox.Show("Preço de venda e custo devem ser numéricos.","Validação",MessageBoxButton.OK,MessageBoxImage.Warning);return;}DialogResult=true;}
 void Cancel_Click(object s,RoutedEventArgs e)=>DialogResult=false;
 public record ProductRow(long Id,string Sku,string Barcode,string Name,string Category,string Unit,decimal SalePrice,decimal CostPrice,decimal Stock,decimal MinStock,decimal MaxStock,decimal Vat,string Location,string Supplier,string Brand,string Model,string Description,string Status);
}
