using Microsoft.Data.Sqlite;using System.Collections.ObjectModel;using System.Text;using System.Windows;using System.Windows.Controls;using System.IO;
namespace AyGest.Wpf;
public partial class PurchasesWindow:Window{
 readonly string _db=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AyGest","aygest.db");readonly ObservableCollection<PurchaseRow> _all=new();
 public PurchasesWindow(){InitializeComponent();Directory.CreateDirectory(Path.GetDirectoryName(_db)!);EnsureSchema();PurchasesGrid.ItemsSource=_all;Load();}
 SqliteConnection C()=>new($"Data Source={_db}");
 void EnsureSchema(){using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="CREATE TABLE IF NOT EXISTS purchase_orders(id INTEGER PRIMARY KEY AUTOINCREMENT,number TEXT NOT NULL UNIQUE,supplier_id INTEGER,supplier_name TEXT NOT NULL,document_number TEXT,subtotal REAL NOT NULL DEFAULT 0,vat REAL NOT NULL DEFAULT 0,total REAL NOT NULL DEFAULT 0,paid REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'Rascunho',received INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,received_at TEXT);CREATE TABLE IF NOT EXISTS purchase_items(id INTEGER PRIMARY KEY AUTOINCREMENT,purchase_id INTEGER NOT NULL,product_id INTEGER,sku TEXT,product_name TEXT NOT NULL,quantity REAL NOT NULL,unit_cost REAL NOT NULL,vat REAL NOT NULL DEFAULT 0,discount REAL NOT NULL DEFAULT 0,total REAL NOT NULL);";q.ExecuteNonQuery();}
 void Load(){_all.Clear();using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="SELECT id,number,substr(created_at,1,10),supplier_name,COALESCE(document_number,''),subtotal,vat,total,paid,CASE WHEN received=1 THEN 'Recebida' ELSE status END,received FROM purchase_orders ORDER BY id DESC";using var r=q.ExecuteReader();while(r.Read())_all.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetDecimal(5),r.GetDecimal(6),r.GetDecimal(7),r.GetDecimal(8),r.GetString(9),r.GetInt32(10)==1));Apply();}
 void Apply(){var t=(SearchBox.Text??"").Trim().ToLowerInvariant();var st=(StatusBox.SelectedItem as ComboBoxItem)?.Content?.ToString();DateTime? from=FromDate.SelectedDate,to=ToDate.SelectedDate;var l=_all.Where(x=>(t==""||$"{x.Number} {x.Supplier} {x.SupplierDocument}".ToLowerInvariant().Contains(t))&&(st=="Todos os estados"||st==null||x.Status==st)&&(!from.HasValue||DateTime.TryParse(x.Date,out var d)&&d.Date>=from.Value.Date)&&(!to.HasValue||DateTime.TryParse(x.Date,out var d2)&&d2.Date<=to.Value.Date)).ToList();PurchasesGrid.ItemsSource=l;CountText.Content=l.Count;TotalText.Content=l.Sum(x=>x.Total).ToString("N2")+" MT";PayableText.Content=l.Sum(x=>Math.Max(0,x.Total-x.Paid)).ToString("N2")+" MT";ReceivedText.Content=l.Count(x=>x.Received).ToString();}
 void FilterChanged(object s,EventArgs e)=>Apply();void Refresh_Click(object s,RoutedEventArgs e)=>Load();
 void New_Click(object s,RoutedEventArgs e){var d=new PurchaseEditorWindow{Owner=this};if(d.ShowDialog()==true)Load();}
 void Open_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is PurchaseRow x)ShowDetails(x.Id);}
 void Receive_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is PurchaseRow x)Receive(x.Id);}
 void Pay_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is PurchaseRow x)Pay(x);}
 void More_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is PurchaseRow x)MessageBox.Show($"Compra {x.Number}\nFornecedor: {x.Supplier}\nDocumento: {x.SupplierDocument}\nEstado: {x.Status}\nTotal: {x.Total:N2} MT\nPago: {x.Paid:N2} MT\nEm aberto: {Math.Max(0,x.Total-x.Paid):N2} MT","Detalhes",MessageBoxButton.OK,MessageBoxImage.Information);}
 void Receive(long id){using var c=C();c.Open();using var tx=c.BeginTransaction();using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="SELECT received,status FROM purchase_orders WHERE id=$id";q.Parameters.AddWithValue("$id",id);using var r=q.ExecuteReader();if(!r.Read()){return;}if(r.GetInt32(0)==1){MessageBox.Show("Esta compra já foi recebida.");return;}r.Close();using var items=c.CreateCommand();items.Transaction=tx;items.CommandText="SELECT product_id,quantity,unit_cost FROM purchase_items WHERE purchase_id=$id";items.Parameters.AddWithValue("$id",id);using var ir=items.ExecuteReader();var rows=new List<(long id,decimal qty,decimal cost)>();while(ir.Read())if(!ir.IsDBNull(0))rows.Add((ir.GetInt64(0),ir.GetDecimal(1),ir.GetDecimal(2)));ir.Close();foreach(var row in rows){using var u=c.CreateCommand();u.Transaction=tx;u.CommandText="UPDATE products SET stock=stock+$q,cost_price=$cost,updated_at=$d WHERE id=$id";u.Parameters.AddWithValue("$q",row.qty);u.Parameters.AddWithValue("$cost",row.cost);u.Parameters.AddWithValue("$d",DateTime.UtcNow.ToString("O"));u.Parameters.AddWithValue("$id",row.id);u.ExecuteNonQuery();using var m=c.CreateCommand();m.Transaction=tx;m.CommandText="INSERT INTO stock_movements(product_id,type,quantity,unit_cost,reference,created_at) VALUES($id,'Compra',$q,$cost,$ref,$d)";m.Parameters.AddWithValue("$id",row.id);m.Parameters.AddWithValue("$q",row.qty);m.Parameters.AddWithValue("$cost",row.cost);m.Parameters.AddWithValue("$ref",id.ToString());m.Parameters.AddWithValue("$d",DateTime.UtcNow.ToString("O"));m.ExecuteNonQuery();}using var up=c.CreateCommand();up.Transaction=tx;up.CommandText="UPDATE purchase_orders SET received=1,status='Recebida',received_at=$d WHERE id=$id";up.Parameters.AddWithValue("$d",DateTime.UtcNow.ToString("O"));up.Parameters.AddWithValue("$id",id);up.ExecuteNonQuery();tx.Commit();Load();}
 void Pay(PurchaseRow x){var v=Microsoft.VisualBasic.Interaction.InputBox($"Valor a pagar (em aberto: {Math.Max(0,x.Total-x.Paid):N2} MT):","Pagamento",Math.Max(0,x.Total-x.Paid).ToString("N2"));if(!decimal.TryParse(v.Replace(".",","),out var amount)||amount<=0)return;using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="UPDATE purchase_orders SET paid=MIN(total,paid+$p),status=CASE WHEN paid+$p>=total THEN 'Paga' ELSE status END WHERE id=$id";q.Parameters.AddWithValue("$p",amount);q.Parameters.AddWithValue("$id",x.Id);q.ExecuteNonQuery();Load();}
 void ShowDetails(long id){using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="SELECT number,supplier_name,document_number,subtotal,vat,total,paid,status FROM purchase_orders WHERE id=$id";q.Parameters.AddWithValue("$id",id);using var r=q.ExecuteReader();if(r.Read())MessageBox.Show($"Compra {r.GetString(0)}\nFornecedor: {r.GetString(1)}\nDocumento: {r.GetString(2)}\nSubtotal: {r.GetDecimal(3):N2} MT\nIVA: {r.GetDecimal(4):N2} MT\nTotal: {r.GetDecimal(5):N2} MT\nPago: {r.GetDecimal(6):N2} MT\nEstado: {r.GetString(7)}","Compra",MessageBoxButton.OK,MessageBoxImage.Information);}
 void Export_Click(object s,RoutedEventArgs e){var sb=new StringBuilder("Número;Data;Fornecedor;Documento;Subtotal;IVA;Total;Pago;Estado\n");foreach(var x in _all)sb.AppendLine($"{x.Number};{x.Date};{x.Supplier};{x.SupplierDocument};{x.Subtotal:N2};{x.Vat:N2};{x.Total:N2};{x.Paid:N2};{x.Status}");var p=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"AyGest_Compras.csv");File.WriteAllText(p,sb.ToString(),Encoding.UTF8);MessageBox.Show("Exportação concluída:\n"+p);}
 public record PurchaseRow(long Id,string Number,string Date,string Supplier,string SupplierDocument,decimal Subtotal,decimal Vat,decimal Total,decimal Paid,string Status,bool Received);
}
