using System.Text.Json;
using Microsoft.Win32;
using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using AyGest.Wpf.Services;
namespace AyGest.Wpf;
public partial class SettingsWindow : Window
{
 readonly Data.AppDb db; readonly BusinessService svc; readonly long companyId;
 public SettingsWindow(Data.AppDb db,BusinessService svc,long companyId){InitializeComponent();this.db=db;this.svc=svc;this.companyId=companyId;Load();}
 void Load(){var c=svc.Query("SELECT name,nuit,address,phone,email,vat_rate FROM companies WHERE id=@i",("@i",companyId)).Rows.First();CompanyName.Text=Convert.ToString(c[0])??"";CompanyNuit.Text=Convert.ToString(c[1])??"";CompanyAddress.Text=Convert.ToString(c[2])??"";CompanyPhone.Text=Convert.ToString(c[3])??"";CompanyEmail.Text=Convert.ToString(c[4])??"";VatRate.Text=Convert.ToString(c[5])??"16";Currency.Text=Get("currency","MZN / MT");Country.Text=Get("country","Moçambique");TimeZone.Text=Get("timezone","Africa/Maputo");DocumentFooter.Text=Get("document_footer","Documento emitido pelo AyGest");LogoPath.Text=Get("logo_path","");InvoicePrefix.Text=Get("invoice_prefix","FT");NextInvoice.Text=Get("next_invoice","1");InvoiceSeries.Text=Get("invoice_series","A");DefaultPayment.Text=Get("default_payment","Dinheiro");DocumentFormat.Text=Get("document_format","A4");AutoInvoice.IsChecked=Get("auto_invoice","true")=="true";RequireCustomer.IsChecked=Get("require_customer","false")=="true";AllowNegativeStock.IsChecked=Get("allow_negative_stock","false")=="true";RoundTotals.IsChecked=Get("round_totals","true")=="true";PrinterA4.Text=Get("printer_a4","");PrinterPos.Text=Get("printer_pos","");PosPort.Text=Get("pos_port","COM2");PosWidth.Text=Get("pos_width","80mm");AutoPrint.IsChecked=Get("auto_print","false")=="true";OpenPdf.IsChecked=Get("open_pdf","true")=="true";ApiUrl.Text=Get("api_url","");TenantId.Text=Get("tenant_id","");ActivationKey.Text=Get("activation_key","");LicensePlan.Text=Get("license_plan","");LicenseStatus.Text=Get("license_status","Não verificada");RequireLogin.IsChecked=Get("require_login","true")=="true";AutoBackup.IsChecked=Get("auto_backup","true")=="true";BackupInterval.Text=Get("backup_interval","24");AuditEnabled.IsChecked=Get("audit_enabled","true")=="true";DbPath.Text=db.Path;SystemInfo.Text=$"Windows {Environment.OSVersion.Version} • {Environment.ProcessorCount} CPU • {(Environment.Is64BitOperatingSystem?"x64":"x86")}";}
 string Get(string k,string fallback)=>svc.Query("SELECT value FROM app_settings WHERE key=@k",("@k",k)).Rows.FirstOrDefault() is { } r?Convert.ToString(r[0])??fallback:fallback;
 void Set(string k,string v)=>svc.Execute("INSERT INTO app_settings(key,value) VALUES(@k,@v) ON CONFLICT(key) DO UPDATE SET value=excluded.value",("@k",k),("@v",v));
 void Save_Click(object s,RoutedEventArgs e){try{if(string.IsNullOrWhiteSpace(CompanyName.Text))throw new InvalidOperationException("O nome da empresa é obrigatório.");if(!decimal.TryParse(VatRate.Text.Replace(',','.'),System.Globalization.NumberStyles.Any,System.Globalization.CultureInfo.InvariantCulture,out var vat)||vat<0||vat>100)throw new InvalidOperationException("IVA inválido.");svc.Execute("UPDATE companies SET name=@n,nuit=@u,address=@a,phone=@p,email=@e,vat_rate=@v WHERE id=@i",("@n",CompanyName.Text.Trim()),("@u",CompanyNuit.Text.Trim()),("@a",CompanyAddress.Text.Trim()),("@p",CompanyPhone.Text.Trim()),("@e",CompanyEmail.Text.Trim()),("@v",vat),("@i",companyId));Set("currency",Currency.Text);Set("country",Country.Text);Set("timezone",TimeZone.Text);Set("document_footer",DocumentFooter.Text);Set("logo_path",LogoPath.Text);Set("invoice_prefix",InvoicePrefix.Text);Set("next_invoice",NextInvoice.Text);Set("invoice_series",InvoiceSeries.Text);Set("default_payment",DefaultPayment.Text);Set("document_format",DocumentFormat.Text);Set("auto_invoice",Bool(AutoInvoice));Set("require_customer",Bool(RequireCustomer));Set("allow_negative_stock",Bool(AllowNegativeStock));Set("round_totals",Bool(RoundTotals));Set("printer_a4",PrinterA4.Text);Set("printer_pos",PrinterPos.Text);Set("pos_port",PosPort.Text);Set("pos_width",PosWidth.Text);Set("auto_print",Bool(AutoPrint));Set("open_pdf",Bool(OpenPdf));Set("api_url",ApiUrl.Text.Trim().TrimEnd('/'));Set("tenant_id",TenantId.Text.Trim());Set("activation_key",ActivationKey.Text.Trim().ToUpperInvariant());Set("license_plan",LicensePlan.Text);Set("license_status",LicenseStatus.Text);Set("require_login",Bool(RequireLogin));Set("auto_backup",Bool(AutoBackup));Set("backup_interval",BackupInterval.Text);Set("audit_enabled",Bool(AuditEnabled));MessageBox.Show("Configurações guardadas com sucesso.","AyGest",MessageBoxButton.OK,MessageBoxImage.Information);DialogResult=true;}catch(Exception ex){MessageBox.Show(ex.Message,"AyGest",MessageBoxButton.OK,MessageBoxImage.Error);}}
 static string Bool(CheckBox c)=>c.IsChecked==true?"true":"false";
 void ChooseLogo_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Imagens|*.png;*.jpg;*.jpeg;*.webp|Todos|*.*"};if(d.ShowDialog()==true)LogoPath.Text=d.FileName;}
 void Backup_Click(object s,RoutedEventArgs e){try{var dir=System.IO.Path.Combine(System.IO.Path.GetDirectoryName(db.Path)!,"backups");Directory.CreateDirectory(dir);var dest=System.IO.Path.Combine(dir,$"aygest-{DateTime.Now:yyyyMMdd-HHmmss}.db");File.Copy(db.Path,dest,false);MessageBox.Show($"Backup criado:\n{dest}","AyGest");}catch(Exception ex){MessageBox.Show(ex.Message,"AyGest",MessageBoxButton.OK,MessageBoxImage.Error);}}
 void OpenData_Click(object s,RoutedEventArgs e)=>Process.Start(new ProcessStartInfo("explorer.exe",System.IO.Path.GetDirectoryName(db.Path)!) {UseShellExecute=true});
 void CheckDb_Click(object s,RoutedEventArgs e){try{using var c=db.Open();using var q=c.CreateCommand();q.CommandText="PRAGMA integrity_check";var result=Convert.ToString(q.ExecuteScalar());MessageBox.Show(result=="ok"?"Base de dados íntegra.":$"Resultado: {result}","AyGest",MessageBoxButton.OK,result=="ok"?MessageBoxImage.Information:MessageBoxImage.Warning);}catch(Exception ex){MessageBox.Show(ex.Message,"AyGest",MessageBoxButton.OK,MessageBoxImage.Error);}}
 void ExportSettings_Click(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="JSON|*.json",FileName="aygest-config.json"};if(d.ShowDialog()!=true)return;var data=svc.Query("SELECT key,value FROM app_settings");var obj=data.Rows.ToDictionary(x=>Convert.ToString(x[0])!,x=>Convert.ToString(x[1])??"");File.WriteAllText(d.FileName,JsonSerializer.Serialize(obj,new JsonSerializerOptions{WriteIndented=true}));}
 void ImportSettings_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="JSON|*.json"};if(d.ShowDialog()!=true)return;var obj=JsonSerializer.Deserialize<Dictionary<string,string>>(File.ReadAllText(d.FileName))??new();foreach(var x in obj)Set(x.Key,x.Value);Load();MessageBox.Show("Configurações importadas.","AyGest");}
 void Activate_Click(object s,RoutedEventArgs e){if(string.IsNullOrWhiteSpace(ApiUrl.Text)||string.IsNullOrWhiteSpace(ActivationKey.Text)){MessageBox.Show("Informe a URL da API e a Activation Key.","AyGest");return;}try{using var api=new OnlineApiClient(ApiUrl.Text.TrimEnd('/'));var result=api.ActivateAsync(ActivationKey.Text.Trim(),DeviceId(),string.IsNullOrWhiteSpace(TenantId.Text)?null:TenantId.Text.Trim()).GetAwaiter().GetResult();LicenseStatus.Text=result.Active?"Activada":"Recusada";LicensePlan.Text=result.Plan??"";if(!string.IsNullOrWhiteSpace(result.TenantId))TenantId.Text=result.TenantId;Set("license_status",LicenseStatus.Text);Set("license_plan",LicensePlan.Text);MessageBox.Show(result.Active?"Licença activada online.":result.Message??"O servidor recusou a licença.","AyGest");}catch(Exception ex){LicenseStatus.Text="Erro de ligação";MessageBox.Show(ex.Message,"AyGest");}}
 void Verify_Click(object s,RoutedEventArgs e){try{using var api=new OnlineApiClient(ApiUrl.Text.TrimEnd('/'));var result=api.VerifyAsync(ActivationKey.Text.Trim(),DeviceId(),string.IsNullOrWhiteSpace(TenantId.Text)?null:TenantId.Text.Trim()).GetAwaiter().GetResult();LicenseStatus.Text=result.Active?"Activa":"Inactiva";LicensePlan.Text=result.Plan??LicensePlan.Text;Set("license_status",LicenseStatus.Text);MessageBox.Show(result.Active?"Licença válida.":result.Message??"Licença inválida.","AyGest");}catch(Exception ex){MessageBox.Show(ex.Message,"AyGest");}}
 void Connection_Click(object s,RoutedEventArgs e){try{if(string.IsNullOrWhiteSpace(ApiUrl.Text)){MessageBox.Show("Configure a URL da API primeiro.");return;}using var api=new OnlineApiClient(ApiUrl.Text.TrimEnd('/'));var ok=api.CheckHealthAsync().GetAwaiter().GetResult();MessageBox.Show(ok?"Servidor online.":"Servidor indisponível.","AyGest");}catch(Exception ex){MessageBox.Show($"Servidor indisponível: {ex.Message}","AyGest");}}
 void Password_Click(object s,RoutedEventArgs e)=>MessageBox.Show("A alteração de palavra-passe deve ser feita no módulo Utilizadores com autenticação de administrador.","AyGest");
 void TestA4_Click(object s,RoutedEventArgs e)=>MessageBox.Show(string.IsNullOrWhiteSpace(PrinterA4.Text)?"Configure a impressora A4 primeiro.":$"Impressora configurada: {PrinterA4.Text}","AyGest");
 void TestPos_Click(object s,RoutedEventArgs e)=>MessageBox.Show(string.IsNullOrWhiteSpace(PrinterPos.Text)&&string.IsNullOrWhiteSpace(PosPort.Text)?"Configure a impressora/porta POS primeiro.":$"POS: {PrinterPos.Text}\nPorta: {PosPort.Text}","AyGest");
 void Defaults_Click(object s,RoutedEventArgs e){Currency.Text="MZN / MT";Country.Text="Moçambique";TimeZone.Text="Africa/Maputo";VatRate.Text="16";InvoicePrefix.Text="FT";InvoiceSeries.Text="A";DefaultPayment.Text="Dinheiro";DocumentFormat.Text="A4";PosPort.Text="COM2";PosWidth.Text="80mm";AutoInvoice.IsChecked=true;OpenPdf.IsChecked=true;RequireLogin.IsChecked=true;AutoBackup.IsChecked=true;AuditEnabled.IsChecked=true;BackupInterval.Text="24";}
 void Cancel_Click(object s,RoutedEventArgs e)=>Close();
 static string DeviceId(){using var sha=System.Security.Cryptography.SHA256.Create();return Convert.ToHexString(sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(Environment.MachineName+"|"+Environment.UserName))).ToLowerInvariant();}
}