using Microsoft.Data.Sqlite;using System.Collections.ObjectModel;using System.Text;using System.Windows;using System.Windows.Controls;using System.IO;
namespace AyGest.Wpf;
public partial class SuppliersWindow:Window{
 readonly string _db=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AyGest","aygest.db");readonly ObservableCollection<SupplierEditorWindow.SupplierRow> _all=new();
 public SuppliersWindow(){InitializeComponent();Directory.CreateDirectory(Path.GetDirectoryName(_db)!);EnsureSchema();GridSuppliers.ItemsSource=_all;Load();}
 SqliteConnection C()=>new($"Data Source={_db}");
 void EnsureSchema(){using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="CREATE TABLE IF NOT EXISTS suppliers(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,tax_id TEXT,phone TEXT,email TEXT,website TEXT,address TEXT,contact_person TEXT,payment_terms TEXT,bank_details TEXT,notes TEXT,status TEXT NOT NULL DEFAULT 'Activo',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS purchase_orders(id INTEGER PRIMARY KEY AUTOINCREMENT,supplier_id INTEGER,total REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'draft',created_at TEXT NOT NULL);";q.ExecuteNonQuery();}
 void Load(){_all.Clear();using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="SELECT s.id,s.code,s.name,COALESCE(s.tax_id,''),COALESCE(s.phone,''),COALESCE(s.email,''),COALESCE(s.website,''),COALESCE(s.address,''),COALESCE(s.contact_person,''),COALESCE(s.payment_terms,''),COALESCE(s.bank_details,''),COALESCE(s.notes,''),s.status,(SELECT COUNT(*) FROM purchase_orders p WHERE p.supplier_id=s.id),(SELECT COALESCE(SUM(p.total),0) FROM purchase_orders p WHERE p.supplier_id=s.id AND p.status NOT IN ('paid','cancelled')) FROM suppliers s ORDER BY s.name";using var r=q.ExecuteReader();while(r.Read())_all.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),r.GetString(8),r.GetString(9),r.GetString(10),r.GetString(11),r.GetString(12),r.GetInt32(13),r.GetDecimal(14)));Apply();}
 void Apply(){var t=(SearchBox.Text??"").Trim().ToLowerInvariant();var st=(StatusBox.SelectedItem as ComboBoxItem)?.Content?.ToString();var list=_all.Where(x=>(t==""||$"{x.Code} {x.Name} {x.TaxId} {x.Phone} {x.Email}".ToLowerInvariant().Contains(t))&&(st=="Todos os estados"||st==null||x.Status==st.Replace("Activos","Activo").Replace("Inactivos","Inactivo"))).ToList();GridSuppliers.ItemsSource=list;CountText.Content=list.Count.ToString();PayableText.Content=list.Sum(x=>x.Payable).ToString("N2")+" MT";}
 void FilterChanged(object s,EventArgs e)=>Apply();void Refresh_Click(object s,RoutedEventArgs e)=>Load();
 void New_Click(object s,RoutedEventArgs e){var d=new SupplierEditorWindow{Owner=this};if(d.ShowDialog()==true){Save(d,null);Load();}}
 void Edit_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is not SupplierEditorWindow.SupplierRow x)return;var d=new SupplierEditorWindow(x){Owner=this};if(d.ShowDialog()==true){Save(d,x.Id);Load();}}
 void Save(SupplierEditorWindow d,long? id){using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText=id==null?"INSERT INTO suppliers(code,name,tax_id,phone,email,website,address,contact_person,payment_terms,bank_details,notes,status,created_at,updated_at) VALUES($c,$n,$t,$p,$e,$w,$a,$cp,$pt,$b,$no,$s,$d,$d)":"UPDATE suppliers SET name=$n,tax_id=$t,phone=$p,email=$e,website=$w,address=$a,contact_person=$cp,payment_terms=$pt,bank_details=$b,notes=$no,status=$s,updated_at=$d WHERE id=$id";if(id!=null)q.Parameters.AddWithValue("$id",id);q.Parameters.AddWithValue("$c",string.IsNullOrWhiteSpace(d.Code)?"FOR"+DateTime.Now.ToString("yyyyMMddHHmmss"):d.Code);q.Parameters.AddWithValue("$n",d.Name);q.Parameters.AddWithValue("$t",d.TaxId);q.Parameters.AddWithValue("$p",d.Phone);q.Parameters.AddWithValue("$e",d.Email);q.Parameters.AddWithValue("$w",d.Website);q.Parameters.AddWithValue("$a",d.Address);q.Parameters.AddWithValue("$cp",d.Contact);q.Parameters.AddWithValue("$pt",d.PaymentTerms);q.Parameters.AddWithValue("$b",d.Bank);q.Parameters.AddWithValue("$no",d.Notes);q.Parameters.AddWithValue("$s",d.Status);q.Parameters.AddWithValue("$d",DateTime.UtcNow.ToString("O"));q.ExecuteNonQuery();}
 void History_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is SupplierEditorWindow.SupplierRow x)MessageBox.Show($"{x.Name}\n\nCompras registadas: {x.PurchaseCount}\nValor em aberto: {x.Payable:N2} MT\n\nO histórico detalhado será integrado ao módulo de Compras.","Histórico do fornecedor",MessageBoxButton.OK,MessageBoxImage.Information);}
 void More_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is not SupplierEditorWindow.SupplierRow x)return;if(MessageBox.Show($"Alterar o estado de {x.Name}?","Fornecedor",MessageBoxButton.YesNo,MessageBoxImage.Question)!=MessageBoxResult.Yes)return;using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="UPDATE suppliers SET status=CASE WHEN status='Activo' THEN 'Inactivo' ELSE 'Activo' END,updated_at=$d WHERE id=$id";q.Parameters.AddWithValue("$id",x.Id);q.Parameters.AddWithValue("$d",DateTime.UtcNow.ToString("O"));q.ExecuteNonQuery();Load();}
 void Export_Click(object s,RoutedEventArgs e){var sb=new StringBuilder("Código;Fornecedor;NUIT;Contacto;Email;Compras;A pagar;Estado\n");foreach(var x in _all)sb.AppendLine($"{x.Code};{x.Name};{x.TaxId};{x.Phone};{x.Email};{x.PurchaseCount};{x.Payable:N2};{x.Status}");var p=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"AyGest_Fornecedores.csv");File.WriteAllText(p,sb.ToString(),Encoding.UTF8);MessageBox.Show("Exportação concluída:\n"+p,"Fornecedores",MessageBoxButton.OK,MessageBoxImage.Information);}
}
