using Microsoft.Data.Sqlite;using System.Security.Cryptography;using System.Text;using System.Windows;using System.Windows.Controls;using System.Collections.ObjectModel;
namespace AyGest.Wpf;
public partial class UsersWindow:Window{
 readonly string _db=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AyGest","aygest.db"); readonly ObservableCollection<UserRow> _rows=new();
 public UsersWindow(){InitializeComponent();Directory.CreateDirectory(Path.GetDirectoryName(_db)!);EnsureSchema();UsersGrid.ItemsSource=_rows;Load();}
 SqliteConnection C()=>new($"Data Source={_db}");
 void EnsureSchema(){using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT NOT NULL UNIQUE,full_name TEXT NOT NULL,email TEXT,role TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Activo',password_hash TEXT NOT NULL,failed_attempts INTEGER NOT NULL DEFAULT 0,last_login TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);";q.ExecuteNonQuery();}
 void Load(){_rows.Clear();using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="SELECT id,username,full_name,email,role,status,COALESCE(last_login,'Nunca') FROM users ORDER BY full_name,username";using var r=q.ExecuteReader();while(r.Read())_rows.Add(new UserRow(r.GetInt64(0),r.GetString(1),r.GetString(2),r.IsDBNull(3)?"":r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6)));ApplyFilter();}
 void ApplyFilter(){var text=(SearchBox.Text??"").Trim().ToLowerInvariant();var role=(RoleFilter.SelectedItem as ComboBoxItem)?.Content?.ToString();var status=(StatusFilter.SelectedItem as ComboBoxItem)?.Content?.ToString();UsersGrid.ItemsSource=_rows.Where(x=>(text==""||$"{x.Username} {x.FullName} {x.Email}".ToLowerInvariant().Contains(text))&&(role=="Todos os perfis"||x.Role==role)&&(status=="Todos os estados"||(status=="Activos"&&x.Status=="Activo")||(status=="Inactivos"&&x.Status!="Activo"))).ToList();}
 void Search_Changed(object s,TextChangedEventArgs e)=>ApplyFilter(); void Filter_Changed(object s,SelectionChangedEventArgs e)=>ApplyFilter(); void Refresh_Click(object s,RoutedEventArgs e)=>Load();
 void New_Click(object s,RoutedEventArgs e){var d=new UserEditorWindow();d.Owner=this;if(d.ShowDialog()==true){Save(d,null);Load();}}
 void Edit_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is not UserRow u)return;var d=new UserEditorWindow(u);d.Owner=this;if(d.ShowDialog()==true){Save(d,u.Id);Load();}}
 void Security_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is UserRow u)MessageBox.Show($"Segurança de {u.Username}: conta activa={u.Status=="Activo"}, tentativas falhadas={GetFailed(u.Id)}.\n\nUse Editar para alterar o perfil ou password.","Segurança",MessageBoxButton.OK,MessageBoxImage.Information);}
 int GetFailed(long id){using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="SELECT failed_attempts FROM users WHERE id=$id";q.Parameters.AddWithValue("$id",id);return Convert.ToInt32(q.ExecuteScalar()??0);}
 void More_Click(object s,RoutedEventArgs e){if((s as Button)?.Tag is not UserRow u)return;var result=MessageBox.Show($"Deseja alterar o estado da conta {u.Username}?","Utilizador",MessageBoxButton.YesNo,MessageBoxImage.Question);if(result==MessageBoxResult.Yes){using var c=C();c.Open();using var q=c.CreateCommand();q.CommandText="UPDATE users SET status=CASE WHEN status='Activo' THEN 'Inactivo' ELSE 'Activo' END,updated_at=$d WHERE id=$id";q.Parameters.AddWithValue("$id",u.Id);q.Parameters.AddWithValue("$d",DateTime.UtcNow.ToString("O"));q.ExecuteNonQuery();Load();}}
 void Save(UserEditorWindow d,long? id){using var c=C();c.Open();using var q=c.CreateCommand();if(id==null){q.CommandText="INSERT INTO users(username,full_name,email,role,status,password_hash,created_at,updated_at) VALUES($u,$n,$e,$r,$s,$p,$d,$d)";}else{q.CommandText="UPDATE users SET full_name=$n,email=$e,role=$r,status=$s,updated_at=$d"+(string.IsNullOrWhiteSpace(d.Password)?"":" ,password_hash=$p")+" WHERE id=$id";q.Parameters.AddWithValue("$id",id);}q.Parameters.AddWithValue("$u",d.Username);q.Parameters.AddWithValue("$n",d.FullName);q.Parameters.AddWithValue("$e",d.Email);q.Parameters.AddWithValue("$r",d.Role);q.Parameters.AddWithValue("$s",d.Status);q.Parameters.AddWithValue("$d",DateTime.UtcNow.ToString("O"));if(!string.IsNullOrWhiteSpace(d.Password))q.Parameters.AddWithValue("$p",Hash(d.Password));q.ExecuteNonQuery();}
 static string Hash(string value){using var sha=SHA256.Create();return Convert.ToHexString(sha.ComputeHash(Encoding.UTF8.GetBytes(value)));}
 public record UserRow(long Id,string Username,string FullName,string Email,string Role,string Status,string LastLogin);
}
