using Microsoft.Data.Sqlite;
var builder=WebApplication.CreateBuilder(args);var app=builder.Build();var adminSecret=Environment.GetEnvironmentVariable("AYGEST_ADMIN_SECRET")??"";
var dbPath=Path.Combine(AppContext.BaseDirectory,"aygest-server.db");
using(var c=new SqliteConnection($"Data Source={dbPath}")){c.Open();using var q=c.CreateCommand();q.CommandText="CREATE TABLE IF NOT EXISTS tenants(id TEXT PRIMARY KEY,name TEXT NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS licenses(key_value TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,plan TEXT NOT NULL,expires_at TEXT,active INTEGER NOT NULL DEFAULT 1,device_id TEXT);";q.ExecuteNonQuery();}
app.MapGet("/health",()=>Results.Ok(new{status="ok",service="AyGest Server",utc=DateTime.UtcNow}));
app.MapPost("/api/v1/licenses/activate",async(HttpRequest req)=>{var body=await System.Text.Json.JsonSerializer.DeserializeAsync<ActivationRequest>(req.Body);if(body is null||string.IsNullOrWhiteSpace(body.Key))return Results.BadRequest(new{active=false,message="Activation Key obrigatória."});using var c=new SqliteConnection($"Data Source={dbPath}");c.Open();using var q=c.CreateCommand();q.CommandText="SELECT tenant_id,plan,expires_at,active FROM licenses WHERE key_value=@k";q.Parameters.AddWithValue("@k",body.Key.Trim().ToUpperInvariant());using var r=q.ExecuteReader();if(!r.Read())return Results.NotFound(new{active=false,message="Activation Key não encontrada."});var tenant=r.GetString(0);var plan=r.GetString(1);var exp=r.IsDBNull(2)?null:r.GetString(2);var active=r.GetInt32(3)==1;if(!active)return Results.Ok(new{active=false,message="Licença revogada."});if(DateTime.TryParse(exp,out var dt)&&dt.ToUniversalTime()<DateTime.UtcNow)return Results.Ok(new{active=false,message="Licença expirada."});r.Close();q.Parameters.Clear();q.CommandText="UPDATE licenses SET device_id=@d WHERE key_value=@k";q.Parameters.AddWithValue("@d",body.DeviceId??"");q.Parameters.AddWithValue("@k",body.Key.Trim().ToUpperInvariant());q.ExecuteNonQuery();return Results.Ok(new{active=true,key=body.Key.Trim().ToUpperInvariant(),tenant_id=tenant,plan,expires_at=exp});});
app.MapPost("/api/v1/licenses/verify",async(HttpRequest req)=>{var body=await System.Text.Json.JsonSerializer.DeserializeAsync<ActivationRequest>(req.Body);if(body is null)return Results.BadRequest();using var c=new SqliteConnection($"Data Source={dbPath}");c.Open();using var q=c.CreateCommand();q.CommandText="SELECT tenant_id,plan,expires_at,active,device_id FROM licenses WHERE key_value=@k";q.Parameters.AddWithValue("@k",body.Key?.Trim().ToUpperInvariant()??"");using var r=q.ExecuteReader();if(!r.Read())return Results.NotFound(new{active=false,message="Licença não encontrada."});var active=r.GetInt32(3)==1;var exp=r.IsDBNull(2)?null:r.GetString(2);var device=r.IsDBNull(4)?null:r.GetString(4);if(DateTime.TryParse(exp,out var dt)&&dt.ToUniversalTime()<DateTime.UtcNow)active=false;if(!string.IsNullOrWhiteSpace(device)&&device!=body.DeviceId)active=false;return Results.Ok(new{active,key=body.Key,tenant_id=r.GetString(0),plan=r.GetString(1),expires_at=exp,message=active?"Licença válida.":"Licença inválida."});});
app.MapPost("/api/v1/admin/licenses",async(HttpRequest req)=>{if(string.IsNullOrWhiteSpace(adminSecret)||!req.Headers.TryGetValue("X-AyGest-Admin",out var supplied)||supplied!=adminSecret)return Results.Unauthorized();var body=await System.Text.Json.JsonSerializer.DeserializeAsync<CreateLicenseRequest>(req.Body);if(body is null||string.IsNullOrWhiteSpace(body.Key)||string.IsNullOrWhiteSpace(body.TenantId))return Results.BadRequest();using var c=new SqliteConnection($"Data Source={dbPath}");c.Open();using var q=c.CreateCommand();q.CommandText="INSERT OR REPLACE INTO tenants(id,name,created_at) VALUES(@t,@n,@d);INSERT OR REPLACE INTO licenses(key_value,tenant_id,plan,expires_at,active) VALUES(@k,@t,@p,@e,1)";q.Parameters.AddWithValue("@t",body.TenantId);q.Parameters.AddWithValue("@n",body.TenantName??body.TenantId);q.Parameters.AddWithValue("@d",DateTime.UtcNow.ToString("O"));q.Parameters.AddWithValue("@k",body.Key.Trim().ToUpperInvariant());q.Parameters.AddWithValue("@p",body.Plan??"Standard");q.Parameters.AddWithValue("@e",(object?)body.ExpiresAt??DBNull.Value);q.ExecuteNonQuery();return Results.Ok(new{created=true,key=body.Key.Trim().ToUpperInvariant(),tenant_id=body.TenantId,plan=body.Plan??"Standard",expires_at=body.ExpiresAt});});
app.Run();
record ActivationRequest(string? Key,string? TenantId,string? DeviceId);record CreateLicenseRequest(string Key,string TenantId,string? TenantName,string? Plan,string? ExpiresAt);