using Microsoft.Data.Sqlite;
using System.Security.Cryptography;
using System.Text;
namespace AyGest.Wpf.Services;
public sealed class BusinessService
{
 readonly Data.AppDb db; public BusinessService(Data.AppDb db)=>this.db=db;
 static string Now()=>DateTime.UtcNow.ToString("O");
 static string Hash(string s)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(s)));
 public long EnsureCompany(string name="Minha Empresa") { using var c=db.Open(); using var q=c.CreateCommand();q.CommandText="SELECT id FROM companies LIMIT 1";var v=q.ExecuteScalar();if(v is not null)return Convert.ToInt64(v);q.CommandText="INSERT INTO companies(name,created_at) VALUES(@n,@d);SELECT last_insert_rowid();";q.Parameters.AddWithValue("@n",name);q.Parameters.AddWithValue("@d",Now());return Convert.ToInt64(q.ExecuteScalar()); }
 public DataTableData Query(string sql,params (string,string)[] p){using var c=db.Open();using var q=c.CreateCommand();q.CommandText=sql;foreach(var a in p)q.Parameters.AddWithValue(a.Item1,a.Item2);using var r=q.ExecuteReader();var t=new DataTableData();for(int i=0;i<r.FieldCount;i++)t.Columns.Add(r.GetName(i));while(r.Read()){var row=new object[r.FieldCount];r.GetValues(row);t.Rows.Add(row);}return t;}
 public void Execute(string sql,params (string,object)[] p){using var c=db.Open();using var q=c.CreateCommand();q.CommandText=sql;foreach(var a in p)q.Parameters.AddWithValue(a.Item1,a.Item2);q.ExecuteNonQuery();}
 public long AddProduct(long company,string name,string sku,string barcode,decimal cost,decimal price,decimal vat,decimal min){using var c=db.Open();using var tx=c.BeginTransaction();using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO products(company_id,name,sku,barcode,cost,price,vat_rate,min_stock) VALUES(@c,@n,@s,@b,@co,@p,@v,@m);SELECT last_insert_rowid();";q.Parameters.AddWithValue("@c",company);q.Parameters.AddWithValue("@n",name);q.Parameters.AddWithValue("@s",sku);q.Parameters.AddWithValue("@b",barcode);q.Parameters.AddWithValue("@co",cost);q.Parameters.AddWithValue("@p",price);q.Parameters.AddWithValue("@v",vat);q.Parameters.AddWithValue("@m",min);var id=Convert.ToInt64(q.ExecuteScalar());q.CommandText="INSERT INTO stock(product_id,quantity) VALUES(@id,0)";q.Parameters.Clear();q.Parameters.AddWithValue("@id",id);q.ExecuteNonQuery();tx.Commit();return id;}
 public string NextInvoice(long company){using var c=db.Open();using var q=c.CreateCommand();q.CommandText="SELECT COUNT(*)+1 FROM invoices WHERE company_id=@c";q.Parameters.AddWithValue("@c",company);return $"FT-{DateTime.Now:yyyy}-{Convert.ToInt64(q.ExecuteScalar()):D6}";}
 public long CreateInvoice(long company,long? customer,IEnumerable<(long product,string description,decimal qty,decimal price,decimal vat)> lines,string method){var ls=lines.ToList();if(ls.Count==0)throw new InvalidOperationException("A factura precisa de itens.");using var c=db.Open();using var tx=c.BeginTransaction();decimal sub=0,vat=0;foreach(var l in ls){if(l.qty<=0||l.price<0)throw new InvalidOperationException("Quantidade/preço inválido.");using var s=c.CreateCommand();s.Transaction=tx;s.CommandText="SELECT quantity FROM stock WHERE product_id=@p";s.Parameters.AddWithValue("@p",l.product);var available=Convert.ToDecimal(s.ExecuteScalar()??0);if(available<l.qty)throw new InvalidOperationException($"Stock insuficiente: {l.description}");sub+=l.qty*l.price;vat+=l.qty*l.price*l.vat/100;}
 using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO invoices(company_id,customer_id,number,subtotal,vat,total,payment_method,created_at) VALUES(@c,@u,@n,@s,@v,@t,@m,@d);SELECT last_insert_rowid();";q.Parameters.AddWithValue("@c",company);q.Parameters.AddWithValue("@u",(object?)customer??DBNull.Value);q.Parameters.AddWithValue("@n",NextInvoice(company));q.Parameters.AddWithValue("@s",sub);q.Parameters.AddWithValue("@v",vat);q.Parameters.AddWithValue("@t",sub+vat);q.Parameters.AddWithValue("@m",method);q.Parameters.AddWithValue("@d",Now());var id=Convert.ToInt64(q.ExecuteScalar());foreach(var l in ls){q.Parameters.Clear();q.CommandText="INSERT INTO invoice_items(invoice_id,product_id,description,quantity,unit_price,vat_rate,line_total) VALUES(@i,@p,@d,@q,@u,@v,@t)";q.Parameters.AddWithValue("@i",id);q.Parameters.AddWithValue("@p",l.product);q.Parameters.AddWithValue("@d",l.description);q.Parameters.AddWithValue("@q",l.qty);q.Parameters.AddWithValue("@u",l.price);q.Parameters.AddWithValue("@v",l.vat);q.Parameters.AddWithValue("@t",l.qty*l.price);q.ExecuteNonQuery();q.Parameters.Clear();q.CommandText="UPDATE stock SET quantity=quantity-@q WHERE product_id=@p";q.Parameters.AddWithValue("@q",l.qty);q.Parameters.AddWithValue("@p",l.product);q.ExecuteNonQuery();q.Parameters.Clear();q.CommandText="INSERT INTO stock_movements(product_id,type,quantity,reference,created_at) VALUES(@p,'SALE',@q,@r,@d)";q.Parameters.AddWithValue("@p",l.product);q.Parameters.AddWithValue("@q",-l.qty);q.Parameters.AddWithValue("@r",id);q.Parameters.AddWithValue("@d",Now());q.ExecuteNonQuery();}tx.Commit();return id;}
 public void CancelInvoice(long id,string reason){if(string.IsNullOrWhiteSpace(reason))throw new InvalidOperationException("Motivo obrigatório.");using var c=db.Open();using var tx=c.BeginTransaction();using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="SELECT status FROM invoices WHERE id=@i";q.Parameters.AddWithValue("@i",id);if(Convert.ToString(q.ExecuteScalar())!="issued")throw new InvalidOperationException("A factura não pode ser anulada.");q.Parameters.Clear();q.CommandText="SELECT product_id,quantity FROM invoice_items WHERE invoice_id=@i";q.Parameters.AddWithValue("@i",id);var items=new List<(long,decimal)>();using(var r=q.ExecuteReader())while(r.Read())items.Add((r.GetInt64(0),r.GetDecimal(1)));foreach(var x in items){q.Parameters.Clear();q.CommandText="UPDATE stock SET quantity=quantity+@q WHERE product_id=@p";q.Parameters.AddWithValue("@q",x.Item2);q.Parameters.AddWithValue("@p",x.Item1);q.ExecuteNonQuery();}q.Parameters.Clear();q.CommandText="UPDATE invoices SET status='cancelled',cancelled_at=@d,cancellation_reason=@r WHERE id=@i";q.Parameters.AddWithValue("@d",Now());q.Parameters.AddWithValue("@r",reason);q.Parameters.AddWithValue("@i",id);q.ExecuteNonQuery();tx.Commit();}
}
public sealed class DataTableData{public List<string> Columns{get;}=new();public List<object[]> Rows{get;}=new();}
